use core;

ALTER TABLE core_tokens
    ADD COLUMN STATE CHAR(64) DEFAULT NULL COMMENT 'State of the token' AFTER APP_CODE,
    ADD COLUMN TOKEN_METADATA JSON DEFAULT NULL COMMENT 'Metadata of the token' AFTER TOKEN,
    ADD COLUMN IS_LIFETIME_TOKEN BOOLEAN NOT NULL DEFAULT 0 COMMENT 'If true, token will not have expiry' AFTER EXPIRES_AT,
    ADD COLUMN UPDATED_BY BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who updated this row' AFTER CREATED_BY,
    ADD COLUMN UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is updated' AFTER CREATED_AT,
    MODIFY COLUMN APP_CODE char(64) NOT NULL COMMENT 'App Code',
    MODIFY COLUMN CLIENT_CODE char(8) NOT NULL COMMENT 'Client Code',
    MODIFY COLUMN TOKEN TEXT DEFAULT NULL COMMENT 'Generated Token',
    MODIFY COLUMN EXPIRES_AT TIMESTAMP NULL COMMENT 'Time when this token will expire';

ALTER TABLE core_tokens
    ADD CONSTRAINT UK_CORE_TOKEN_STATE UNIQUE (STATE);
