use core;

ALTER TABLE `core`.`core_tokens`
    DROP CONSTRAINT `UK_CORE_TOKEN_STATE`;
ALTER TABLE `core`.`core_tokens`
    ADD CONSTRAINT `UK_CORE_TOKEN_STATE_TOKEN_TYPE` UNIQUE (`STATE`, `TOKEN_TYPE`);