CREATE TABLE IF NOT EXISTS entity_integrations
(
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
  CLIENT_CODE CHAR(8) NOT NULL COMMENT 'Client Code',
  APP_CODE CHAR(8) NOT NULL COMMENT 'App Code',
  TARGET VARCHAR(255) NOT NULL COMMENT 'Target',
  SECONDARY_TARGET VARCHAR(255) COMMENT 'Secondary target',
  IN_SOURCE VARCHAR(255) COMMENT 'Source',
  IN_SOURCE_TYPE ENUM('FACEBOOK_FORM', 'GOOGLE_FORM', 'WEBSITE') NOT NULL COMMENT 'Type of source that integration is generated',
  CREATED_BY BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who created this row',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',
  UPDATED_BY BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who updated this row',
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is updated'
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
