USE `entity_collector`;

CREATE TABLE IF NOT EXISTS `entity_collector_log` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `ENTITY_INTEGRATION_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Entity integration ID',
  `INCOMING_ENTITY_DATA` JSON DEFAULT NULL COMMENT 'Entity Data',
  `IP_ADDRESS` VARCHAR(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Ip address',
  `OUTGOING_ENTITY_DATA` JSON DEFAULT NULL COMMENT 'Entity data forwarded to target',
  `STATUS` ENUM('IN_PROGRESS','REJECTED','SUCCESS','WITH_ERRORS') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Status of the entity transfer',
  `STATUS_MESSAGE` TEXT COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Message given for the status',
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is updated',
  PRIMARY KEY (`ID`),
  KEY `FK1_COLLECTOR_ENTITY_INTEGRATION_ID` (`ENTITY_INTEGRATION_ID`),
  CONSTRAINT `FK1_COLLECTOR_ENTITY_INTEGRATION_ID` FOREIGN KEY (`ENTITY_INTEGRATION_ID`)
    REFERENCES `entity_integrations` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
