use security;

DROP TABLE IF EXISTS `security_app_customer_package`;
DROP TABLE IF EXISTS `security_app_customer_user_role`;
DROP TABLE IF EXISTS `security_app_reg_customer_access`;
DROP TABLE IF EXISTS `security_app_package`;
DROP TABLE IF EXISTS `security_app_user_role`;


ALTER TABLE `security`.`security_app`
ADD COLUMN `APP_USAGE_TYPE` ENUM('S', 'B', 'B2C', 'B2B', 'B2X', 'B2B2B', 'B2B2C', 'B2B2X', 'B2X2C', 'B2X2X') NOT NULL DEFAULT 'S' COMMENT 'S - Standalone (Mostly for sites), B - Business only, B to C Consumer, B Business, X Any, and so on so forth.' AFTER `THUMB_URL`;

ALTER TABLE `security`.`security_client`
ADD COLUMN `BUSINESS_TYPE` CHAR(10) NOT NULL DEFAULT 'COMMON' COMMENT 'At each llevel of business client, customer and consumer there can be different business types.' AFTER `STATUS_CODE`;

DROP TABLE IF EXISTS `security_app_reg_access`;

CREATE TABLE `security_app_reg_access` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',

    `CLIENT_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Client ID',
    `CLIENT_TYPE` CHAR(4) NOT NULL DEFAULT 'BUS' COMMENT 'Client type',
    `APP_ID` BIGINT UNSIGNED NOT NULL COMMENT 'App ID',
    `ALLOW_APP_ID` BIGINT UNSIGNED NOT NULL COMMENT 'App ID of the dependent app',
    `LEVEL` ENUM('CLIENT', 'CUSTOMER', 'CONSUMER') NOT NULL DEFAULT 'CLIENT' COMMENT 'Access level',
    `BUSINESS_TYPE` CHAR(10) NOT NULL DEFAULT 'COMMON' COMMENT 'Business type', 
    
    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who created this row',
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',
    `UPDATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who updated this row',
    `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is updated',

    PRIMARY KEY (`ID`),
    UNIQUE KEY (`CLIENT_ID`, `APP_ID`, `ALLOW_APP_ID`, `CLIENT_TYPE`, `LEVEL`, `BUSINESS_TYPE`),
    CONSTRAINT `FK1_APP_REG_ACC_CLNT_ID` FOREIGN KEY (`CLIENT_ID`) REFERENCES `security_client` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK2_APP_REG_ACC_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `security_app` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK3_APP_REG_ACC_ALLOW_APP_ID` FOREIGN KEY (`ALLOW_APP_ID`) REFERENCES `security_app` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK4_APP_REG_ACC_CLIENT_TYPE` FOREIGN KEY (`CLIENT_TYPE`) REFERENCES `security_client_type` (`CODE`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `security_app_reg_package`;

CREATE TABLE `security_app_reg_package` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',

    `CLIENT_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Client ID',
    `CLIENT_TYPE` CHAR(4) NOT NULL DEFAULT 'BUS' COMMENT 'Client type',
    `APP_ID` BIGINT UNSIGNED NOT NULL COMMENT 'App ID',
    `PACKAGE_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Package ID',
    `LEVEL` ENUM('CLIENT', 'CUSTOMER', 'CONSUMER') NOT NULL DEFAULT 'CLIENT' COMMENT 'Access level',
    `BUSINESS_TYPE` CHAR(10) NOT NULL DEFAULT 'COMMON' COMMENT 'Business type', 

    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who created this row',
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',
    `UPDATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who updated this row',
    `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is updated',

    PRIMARY KEY (`ID`),

    UNIQUE KEY (`CLIENT_ID`, `APP_ID`, `PACKAGE_ID`, `CLIENT_TYPE`, `LEVEL`, `BUSINESS_TYPE`),
    CONSTRAINT `FK1_APP_REG_PKG_CLNT_ID` FOREIGN KEY (`CLIENT_ID`) REFERENCES `security_client` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK2_APP_REG_PKG_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `security_app` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK3_APP_REG_PKG_PKG_ID` FOREIGN KEY (`PACKAGE_ID`) REFERENCES `security_package` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK4_APP_REG_PKG_CLIENT_TYPE` FOREIGN KEY (`CLIENT_TYPE`) REFERENCES `security_client_type` (`CODE`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `security_app_reg_user_role`;

CREATE TABLE `security_app_reg_user_role` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',

    `CLIENT_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Client ID',
    `CLIENT_TYPE` CHAR(4) NOT NULL DEFAULT 'BUS' COMMENT 'Client type',
    `APP_ID` BIGINT UNSIGNED NOT NULL COMMENT 'App ID',
    `ROLE_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Role ID',
    `LEVEL` ENUM('CLIENT', 'CUSTOMER', 'CONSUMER') NOT NULL DEFAULT 'CLIENT' COMMENT 'Access level',
    `BUSINESS_TYPE` CHAR(10) NOT NULL DEFAULT 'COMMON' COMMENT 'Business type', 

    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who created this row',
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',
    `UPDATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who updated this row',
    `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is updated',

    PRIMARY KEY (`ID`),

    UNIQUE KEY (`CLIENT_ID`, `APP_ID`, `ROLE_ID`, `CLIENT_TYPE`, `LEVEL`, `BUSINESS_TYPE`),
    CONSTRAINT `FK1_APP_REG_ROLE_CLNT_ID` FOREIGN KEY (`CLIENT_ID`) REFERENCES `security_client` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK2_APP_REG_ROLE_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `security_app` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK3_APP_REG_ROLE_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `security_role` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK4_APP_REG_ROLE_CLIENT_TYPE` FOREIGN KEY (`CLIENT_TYPE`) REFERENCES `security_client_type` (`CODE`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;