use security;

DROP TABLE IF EXISTS `security_client_address`;
DROP TABLE IF EXISTS `security_user_address`;
DROP TABLE IF EXISTS `security_address`;

CREATE TABLE `security_address` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',

    `ADDRESS_TYPE` VARCHAR(128) DEFAULT NULL COMMENT 'Address type',
    `ADDRESS_COMMENT` VARCHAR(512) DEFAULT NULL COMMENT 'Address comment',

    `ADDRESS_LINE1` VARCHAR(512) DEFAULT NULL COMMENT 'Address line 1',
    `ADDRESS_LINE2` VARCHAR(512) DEFAULT NULL COMMENT 'Address line 2',
    `ADDRESS_LINE3` VARCHAR(512) DEFAULT NULL COMMENT 'Address line 3',
    `CITY` VARCHAR(256) DEFAULT NULL COMMENT 'City',
    `STATE` VARCHAR(256) DEFAULT NULL COMMENT 'State',
    `COUNTRY` VARCHAR(256) DEFAULT NULL COMMENT 'Country',
    `PIN` VARCHAR(32) DEFAULT NULL COMMENT 'Pin code',
    `PHONE` VARCHAR(32) DEFAULT NULL COMMENT 'Phone number',
    `LANDMARK` VARCHAR(512) DEFAULT NULL COMMENT 'Landmark',

    `LATITUDE` DECIMAL(10, 8) DEFAULT NULL COMMENT 'Latitude',
    `LONGITUDE` DECIMAL(11, 8) DEFAULT NULL COMMENT 'Longitude',

    `MAP_LOCATION` TEXT DEFAULT NULL COMMENT 'Map location',


    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who created this row',
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',
    `UPDATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who last updated this row',
    `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Time when this row is last updated',

    PRIMARY KEY (`ID`)
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE `security_user_address` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',

    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT 'User ID',
    `ADDRESS_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Address ID',

    PRIMARY KEY (`ID`),
    CONSTRAINT `FK1_USER_ADDRESS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `security_user` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK2_USER_ADDRESS_ADDRESS_ID` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `security_address` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE `security_client_address` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',

    `CLIENT_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Client ID',
    `ADDRESS_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Address ID',

    PRIMARY KEY (`ID`),
    CONSTRAINT `FK1_CLIENT_ADDRESS_CLIENT_ID` FOREIGN KEY (`CLIENT_ID`) REFERENCES `security_client` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK2_CLIENT_ADDRESS_ADDRESS_ID` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `security_address` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

