ALTER TABLE `security`.`security_user`
    ADD COLUMN `PIN` VARCHAR(512) COMMENT 'PIN message digested string' AFTER `PASSWORD_HASHED`,
    ADD COLUMN `PIN_HASHED` TINYINT DEFAULT 1 COMMENT 'PIN stored is hashed or not' AFTER `PIN`,
    ADD COLUMN `NO_PIN_FAILED_ATTEMPT` SMALLINT DEFAULT 0 COMMENT 'No of failed attempts for PIN' AFTER `NO_FAILED_ATTEMPT`,
    ADD COLUMN `NO_OTP_RESEND_ATTEMPT` SMALLINT DEFAULT 0 COMMENT 'No of Resend attempts for OTP' AFTER `NO_PIN_FAILED_ATTEMPT`,
    ADD COLUMN `NO_OTP_FAILED_ATTEMPT` SMALLINT DEFAULT 0 COMMENT 'No of failed attempts for OTP' AFTER `NO_OTP_RESEND_ATTEMPT`,
    ADD COLUMN `LOCKED_UNTIL` TIMESTAMP NULL COMMENT 'If user is blocked based on STATUS_CODE, until when this will indicate' AFTER `STATUS_CODE`,
    ADD COLUMN `LOCKED_DUE_TO` VARCHAR(512) NULL COMMENT 'Reason for the user blocking action' AFTER LOCKED_UNTIL;
