DROP TABLE IF EXISTS `security`.`security_plan_app`;

ALTER TABLE `security`.`security_plan`
    ADD COLUMN `APP_ID` BIGINT UNSIGNED NULL DEFAULT NULL AFTER `CLIENT_ID`,
    ADD CONSTRAINT `FK1_PLAN_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `security`.`security_app` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `security`.`security_plan`
    ADD COLUMN `PREPAID` TINYINT(1) NOT NULL DEFAULT '0' AFTER `DESCRIPTION`;

ALTER TABLE `security`.`security_plan_cycle`
    DROP COLUMN `INTERVAL`,
    ADD COLUMN `INTERVAL_TYPE` ENUM('MONTH', 'QUARTER', 'ANNUAL', 'WEEK') NOT NULL AFTER `TAX5_NAME`,
    ADD COLUMN `REMiNDER_INTERVAL_DAYS` INT NULL DEFAULT NULL AFTER `INTERVAL_TYPE`,
    ADD COLUMN `PAYMENT_TERMS_DAYS` INT NOT NULL DEFAULT 7 AFTER `REMiNDER_INTERVAL_DAYS`;

ALTER TABLE security.security_invoice
  ADD COLUMN PERIOD_START TIMESTAMP NULL COMMENT 'Service period start (UTC)',
  ADD COLUMN PERIOD_END   TIMESTAMP NULL COMMENT 'Service period end (UTC)';

ALTER TABLE security.security_invoice
  ADD CONSTRAINT CHK_INVOICE_PERIOD_VALID
  CHECK (PERIOD_START IS NULL OR PERIOD_END IS NULL OR PERIOD_START < PERIOD_END);

CREATE UNIQUE INDEX UK_INVOICE_PERIOD
  ON security.security_invoice (CLIENT_ID, PLAN_ID, CYCLE_ID, PERIOD_START);
