DROP TABLE IF EXISTS `security`.`security_plan_app`;

ALTER TABLE `security`.`security_plan`
    ADD COLUMN `APP_ID` BIGINT UNSIGNED NULL DEFAULT NULL AFTER `CLIENT_ID`,
    ADD CONSTRAINT `FK1_PLAN_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `security`.`security_app` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `security`.`security_plan`
    ADD COLUMN `PREPAID` TINYINT(1) NOT NULL DEFAULT '0' AFTER `DESCRIPTION`;
