USE `security`;

CREATE TABLE `security`.`security_client_manager`
(
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `CLIENT_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Client ID for which this profile belongs to',
    `MANAGER_ID` BIGINT UNSIGNED NOT NULL COMMENT 'Manager ID for the client.',
    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID of the user who created this row',
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when this row is created',

    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK1_CLIENT_MANAGER_CLIENT_ID_MANAGER_ID` (`CLIENT_ID`, `MANAGER_ID`),

    CONSTRAINT `FK1_CLIENT_MANAGER_CLIENT_ID` FOREIGN KEY (`CLIENT_ID`) REFERENCES `security`.`security_client` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK2_CLIENT_MANAGER_USER_ID` FOREIGN KEY (`MANAGER_ID`) REFERENCES `security`.`security_user` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB
  DEFAULT CHARSET = `utf8mb4`;
