use security;

CREATE TABLE IF NOT EXISTS `security_client_activity` (
    ID            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    CLIENT_ID     BIGINT UNSIGNED NOT NULL COMMENT 'FK to security_client',
    ACTIVITY_NAME VARCHAR(256) NOT NULL COMMENT 'Short label for the activity',
    DESCRIPTION   TEXT NULL COMMENT 'Optional detail',
    CREATED_BY    BIGINT UNSIGNED DEFAULT NULL,
    CREATED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY IDX_CLIENT_ACTIVITY_CLIENT     (CLIENT_ID),
    KEY IDX_CLIENT_ACTIVITY_CREATED_BY (CREATED_BY),
    CONSTRAINT FK_CLIENT_ACTIVITY_CLIENT
        FOREIGN KEY (CLIENT_ID) REFERENCES security_client (ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
