/*
 * This file is generated by jOOQ.
 */
package com.fincity.sass.worker.jooq;


import com.fincity.sass.worker.jooq.tables.WorkerClientScheduleControls;
import com.fincity.sass.worker.jooq.tables.WorkerTasks;


/**
 * Convenience access to all tables in worker.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>worker.worker_client_schedule_controls</code>.
     */
    public static final WorkerClientScheduleControls WORKER_CLIENT_SCHEDULE_CONTROLS = WorkerClientScheduleControls.WORKER_CLIENT_SCHEDULE_CONTROLS;

    /**
     * The table <code>worker.worker_tasks</code>.
     */
    public static final WorkerTasks WORKER_TASKS = WorkerTasks.WORKER_TASKS;
}
