/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * Status
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum SecurityWalletBudgetStatus implements EnumType {

    ACTIVE("ACTIVE"),

    INACTIVE("INACTIVE"),

    DELETED("DELETED");

    private final String literal;

    private SecurityWalletBudgetStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static SecurityWalletBudgetStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(SecurityWalletBudgetStatus.class, literal);
    }
}
