/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.tables.SecurityProfileRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityProfileRoleRecord extends UpdatableRecordImpl<SecurityProfileRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_profile_role.ID</code>. Primary key
     */
    public SecurityProfileRoleRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_profile_role.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_profile_role.PROFILE_ID</code>.
     * Profile ID for which this role belongs to
     */
    public SecurityProfileRoleRecord setProfileId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_profile_role.PROFILE_ID</code>.
     * Profile ID for which this role belongs to
     */
    public ULong getProfileId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_profile_role.ROLE_ID</code>. Role ID
     * for which this profile belongs to
     */
    public SecurityProfileRoleRecord setRoleId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_profile_role.ROLE_ID</code>. Role ID
     * for which this profile belongs to
     */
    public ULong getRoleId() {
        return (ULong) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityProfileRoleRecord
     */
    public SecurityProfileRoleRecord() {
        super(SecurityProfileRole.SECURITY_PROFILE_ROLE);
    }

    /**
     * Create a detached, initialised SecurityProfileRoleRecord
     */
    public SecurityProfileRoleRecord(ULong id, ULong profileId, ULong roleId) {
        super(SecurityProfileRole.SECURITY_PROFILE_ROLE);

        setId(id);
        setProfileId(profileId);
        setRoleId(roleId);
        resetChangedOnNotNull();
    }
}
