/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.tables.SecurityIntegrationTokens;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityIntegrationTokensRecord extends UpdatableRecordImpl<SecurityIntegrationTokensRecord> implements Record7<ULong, ULong, ULong, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_integration_tokens.ID</code>. Primary
     * key
     */
    public SecurityIntegrationTokensRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_integration_tokens.ID</code>. Primary
     * key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>security.security_integration_tokens.INTEGRATION_ID</code>.
     * Integration ID
     */
    public SecurityIntegrationTokensRecord setIntegrationId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_integration_tokens.INTEGRATION_ID</code>.
     * Integration ID
     */
    public ULong getIntegrationId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_integration_tokens.USER_ID</code>.
     * User ID
     */
    public SecurityIntegrationTokensRecord setUserId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_integration_tokens.USER_ID</code>.
     * User ID
     */
    public ULong getUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>security.security_integration_tokens.TOKEN</code>. Token
     */
    public SecurityIntegrationTokensRecord setToken(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_integration_tokens.TOKEN</code>. Token
     */
    public String getToken() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>security.security_integration_tokens.REFRESH_TOKEN</code>. Refresh
     * Token
     */
    public SecurityIntegrationTokensRecord setRefreshToken(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_integration_tokens.REFRESH_TOKEN</code>. Refresh
     * Token
     */
    public String getRefreshToken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>security.security_integration_tokens.EXPIRES_AT</code>.
     * Token expiration time
     */
    public SecurityIntegrationTokensRecord setExpiresAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_integration_tokens.EXPIRES_AT</code>.
     * Token expiration time
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>security.security_integration_tokens.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityIntegrationTokensRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_integration_tokens.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<ULong, ULong, ULong, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<ULong, ULong, ULong, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.ID;
    }

    @Override
    public Field<ULong> field2() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.INTEGRATION_ID;
    }

    @Override
    public Field<ULong> field3() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.TOKEN;
    }

    @Override
    public Field<String> field5() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.REFRESH_TOKEN;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.EXPIRES_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS.CREATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public ULong component2() {
        return getIntegrationId();
    }

    @Override
    public ULong component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getToken();
    }

    @Override
    public String component5() {
        return getRefreshToken();
    }

    @Override
    public LocalDateTime component6() {
        return getExpiresAt();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public ULong value2() {
        return getIntegrationId();
    }

    @Override
    public ULong value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getToken();
    }

    @Override
    public String value5() {
        return getRefreshToken();
    }

    @Override
    public LocalDateTime value6() {
        return getExpiresAt();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public SecurityIntegrationTokensRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord value2(ULong value) {
        setIntegrationId(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord value3(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord value4(String value) {
        setToken(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord value5(String value) {
        setRefreshToken(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord value6(LocalDateTime value) {
        setExpiresAt(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SecurityIntegrationTokensRecord values(ULong value1, ULong value2, ULong value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityIntegrationTokensRecord
     */
    public SecurityIntegrationTokensRecord() {
        super(SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS);
    }

    /**
     * Create a detached, initialised SecurityIntegrationTokensRecord
     */
    public SecurityIntegrationTokensRecord(ULong id, ULong integrationId, ULong userId, String token, String refreshToken, LocalDateTime expiresAt, LocalDateTime createdAt) {
        super(SecurityIntegrationTokens.SECURITY_INTEGRATION_TOKENS);

        setId(id);
        setIntegrationId(integrationId);
        setUserId(userId);
        setToken(token);
        setRefreshToken(refreshToken);
        setExpiresAt(expiresAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
