/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.enums.SecurityAppAppAccessType;
import com.fincity.security.jooq.enums.SecurityAppAppType;
import com.fincity.security.jooq.enums.SecurityAppAppUsageType;
import com.fincity.security.jooq.tables.SecurityApp;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityAppRecord extends UpdatableRecordImpl<SecurityAppRecord> implements Record12<ULong, ULong, String, String, SecurityAppAppType, SecurityAppAppAccessType, String, SecurityAppAppUsageType, ULong, LocalDateTime, ULong, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_app.ID</code>. Primary key
     */
    public SecurityAppRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_app.CLIENT_ID</code>. Client ID
     */
    public SecurityAppRecord setClientId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.CLIENT_ID</code>. Client ID
     */
    public ULong getClientId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_app.APP_NAME</code>. Name of the
     * application
     */
    public SecurityAppRecord setAppName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.APP_NAME</code>. Name of the
     * application
     */
    public String getAppName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_app.APP_CODE</code>. Code of the
     * application
     */
    public SecurityAppRecord setAppCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.APP_CODE</code>. Code of the
     * application
     */
    public String getAppCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>security.security_app.APP_TYPE</code>. Application type
     */
    public SecurityAppRecord setAppType(SecurityAppAppType value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.APP_TYPE</code>. Application type
     */
    public SecurityAppAppType getAppType() {
        return (SecurityAppAppType) get(4);
    }

    /**
     * Setter for <code>security.security_app.APP_ACCESS_TYPE</code>.
     */
    public SecurityAppRecord setAppAccessType(SecurityAppAppAccessType value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.APP_ACCESS_TYPE</code>.
     */
    public SecurityAppAppAccessType getAppAccessType() {
        return (SecurityAppAppAccessType) get(5);
    }

    /**
     * Setter for <code>security.security_app.THUMB_URL</code>.
     */
    public SecurityAppRecord setThumbUrl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.THUMB_URL</code>.
     */
    public String getThumbUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>security.security_app.APP_USAGE_TYPE</code>. S -
     * Standalone (Mostly for sites), B - Business only, B to C Consumer, B
     * Business, X Any, and so on so forth.
     */
    public SecurityAppRecord setAppUsageType(SecurityAppAppUsageType value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.APP_USAGE_TYPE</code>. S -
     * Standalone (Mostly for sites), B - Business only, B to C Consumer, B
     * Business, X Any, and so on so forth.
     */
    public SecurityAppAppUsageType getAppUsageType() {
        return (SecurityAppAppUsageType) get(7);
    }

    /**
     * Setter for <code>security.security_app.CREATED_BY</code>. ID of the user
     * who created this row
     */
    public SecurityAppRecord setCreatedBy(ULong value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.CREATED_BY</code>. ID of the user
     * who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>security.security_app.CREATED_AT</code>. Time when this
     * row is created
     */
    public SecurityAppRecord setCreatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.CREATED_AT</code>. Time when this
     * row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>security.security_app.UPDATED_BY</code>. ID of the user
     * who updated this row
     */
    public SecurityAppRecord setUpdatedBy(ULong value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.UPDATED_BY</code>. ID of the user
     * who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(10);
    }

    /**
     * Setter for <code>security.security_app.UPDATED_AT</code>. Time when this
     * row is updated
     */
    public SecurityAppRecord setUpdatedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app.UPDATED_AT</code>. Time when this
     * row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<ULong, ULong, String, String, SecurityAppAppType, SecurityAppAppAccessType, String, SecurityAppAppUsageType, ULong, LocalDateTime, ULong, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<ULong, ULong, String, String, SecurityAppAppType, SecurityAppAppAccessType, String, SecurityAppAppUsageType, ULong, LocalDateTime, ULong, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return SecurityApp.SECURITY_APP.ID;
    }

    @Override
    public Field<ULong> field2() {
        return SecurityApp.SECURITY_APP.CLIENT_ID;
    }

    @Override
    public Field<String> field3() {
        return SecurityApp.SECURITY_APP.APP_NAME;
    }

    @Override
    public Field<String> field4() {
        return SecurityApp.SECURITY_APP.APP_CODE;
    }

    @Override
    public Field<SecurityAppAppType> field5() {
        return SecurityApp.SECURITY_APP.APP_TYPE;
    }

    @Override
    public Field<SecurityAppAppAccessType> field6() {
        return SecurityApp.SECURITY_APP.APP_ACCESS_TYPE;
    }

    @Override
    public Field<String> field7() {
        return SecurityApp.SECURITY_APP.THUMB_URL;
    }

    @Override
    public Field<SecurityAppAppUsageType> field8() {
        return SecurityApp.SECURITY_APP.APP_USAGE_TYPE;
    }

    @Override
    public Field<ULong> field9() {
        return SecurityApp.SECURITY_APP.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return SecurityApp.SECURITY_APP.CREATED_AT;
    }

    @Override
    public Field<ULong> field11() {
        return SecurityApp.SECURITY_APP.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return SecurityApp.SECURITY_APP.UPDATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public ULong component2() {
        return getClientId();
    }

    @Override
    public String component3() {
        return getAppName();
    }

    @Override
    public String component4() {
        return getAppCode();
    }

    @Override
    public SecurityAppAppType component5() {
        return getAppType();
    }

    @Override
    public SecurityAppAppAccessType component6() {
        return getAppAccessType();
    }

    @Override
    public String component7() {
        return getThumbUrl();
    }

    @Override
    public SecurityAppAppUsageType component8() {
        return getAppUsageType();
    }

    @Override
    public ULong component9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public ULong component11() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public ULong value2() {
        return getClientId();
    }

    @Override
    public String value3() {
        return getAppName();
    }

    @Override
    public String value4() {
        return getAppCode();
    }

    @Override
    public SecurityAppAppType value5() {
        return getAppType();
    }

    @Override
    public SecurityAppAppAccessType value6() {
        return getAppAccessType();
    }

    @Override
    public String value7() {
        return getThumbUrl();
    }

    @Override
    public SecurityAppAppUsageType value8() {
        return getAppUsageType();
    }

    @Override
    public ULong value9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public ULong value11() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdatedAt();
    }

    @Override
    public SecurityAppRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public SecurityAppRecord value2(ULong value) {
        setClientId(value);
        return this;
    }

    @Override
    public SecurityAppRecord value3(String value) {
        setAppName(value);
        return this;
    }

    @Override
    public SecurityAppRecord value4(String value) {
        setAppCode(value);
        return this;
    }

    @Override
    public SecurityAppRecord value5(SecurityAppAppType value) {
        setAppType(value);
        return this;
    }

    @Override
    public SecurityAppRecord value6(SecurityAppAppAccessType value) {
        setAppAccessType(value);
        return this;
    }

    @Override
    public SecurityAppRecord value7(String value) {
        setThumbUrl(value);
        return this;
    }

    @Override
    public SecurityAppRecord value8(SecurityAppAppUsageType value) {
        setAppUsageType(value);
        return this;
    }

    @Override
    public SecurityAppRecord value9(ULong value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SecurityAppRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SecurityAppRecord value11(ULong value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public SecurityAppRecord value12(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SecurityAppRecord values(ULong value1, ULong value2, String value3, String value4, SecurityAppAppType value5, SecurityAppAppAccessType value6, String value7, SecurityAppAppUsageType value8, ULong value9, LocalDateTime value10, ULong value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAppRecord
     */
    public SecurityAppRecord() {
        super(SecurityApp.SECURITY_APP);
    }

    /**
     * Create a detached, initialised SecurityAppRecord
     */
    public SecurityAppRecord(ULong id, ULong clientId, String appName, String appCode, SecurityAppAppType appType, SecurityAppAppAccessType appAccessType, String thumbUrl, SecurityAppAppUsageType appUsageType, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityApp.SECURITY_APP);

        setId(id);
        setClientId(clientId);
        setAppName(appName);
        setAppCode(appCode);
        setAppType(appType);
        setAppAccessType(appAccessType);
        setThumbUrl(thumbUrl);
        setAppUsageType(appUsageType);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
