/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.tables.SecurityAppRegIntegrationTokens;

import java.time.LocalDateTime;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAppRegIntegrationTokensRecord extends UpdatableRecordImpl<SecurityAppRegIntegrationTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_app_reg_integration_tokens.ID</code>.
     * Primary key
     */
    public SecurityAppRegIntegrationTokensRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_integration_tokens.ID</code>.
     * Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.INTEGRATION_ID</code>.
     * Integration ID
     */
    public SecurityAppRegIntegrationTokensRecord setIntegrationId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.INTEGRATION_ID</code>.
     * Integration ID
     */
    public ULong getIntegrationId() {
        return (ULong) get(1);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.AUTH_CODE</code>. User
     * Consent Auth Code
     */
    public SecurityAppRegIntegrationTokensRecord setAuthCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.AUTH_CODE</code>. User
     * Consent Auth Code
     */
    public String getAuthCode() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.STATE</code>. Session
     * id for login
     */
    public SecurityAppRegIntegrationTokensRecord setState(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.STATE</code>. Session
     * id for login
     */
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.REQUEST_PARAM</code>.
     * url from request made
     */
    public SecurityAppRegIntegrationTokensRecord setRequestParam(Map value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.REQUEST_PARAM</code>.
     * url from request made
     */
    public Map getRequestParam() {
        return (Map) get(4);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.TOKEN</code>. Token
     */
    public SecurityAppRegIntegrationTokensRecord setToken(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.TOKEN</code>. Token
     */
    public String getToken() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.REFRESH_TOKEN</code>.
     * Refresh Token
     */
    public SecurityAppRegIntegrationTokensRecord setRefreshToken(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.REFRESH_TOKEN</code>.
     * Refresh Token
     */
    public String getRefreshToken() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.EXPIRES_AT</code>.
     * Token expiration time
     */
    public SecurityAppRegIntegrationTokensRecord setExpiresAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.EXPIRES_AT</code>.
     * Token expiration time
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.TOKEN_METADATA</code>.
     * Token metadata
     */
    public SecurityAppRegIntegrationTokensRecord setTokenMetadata(Map value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.TOKEN_METADATA</code>.
     * Token metadata
     */
    public Map getTokenMetadata() {
        return (Map) get(8);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.USERNAME</code>.
     * Username
     */
    public SecurityAppRegIntegrationTokensRecord setUsername(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.USERNAME</code>.
     * Username
     */
    public String getUsername() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.USER_METADATA</code>.
     * User metadata
     */
    public SecurityAppRegIntegrationTokensRecord setUserMetadata(Map value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.USER_METADATA</code>.
     * User metadata
     */
    public Map getUserMetadata() {
        return (Map) get(10);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityAppRegIntegrationTokensRecord setCreatedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public SecurityAppRegIntegrationTokensRecord setCreatedBy(ULong value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(12);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public SecurityAppRegIntegrationTokensRecord setUpdatedBy(ULong value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(13);
    }

    /**
     * Setter for
     * <code>security.security_app_reg_integration_tokens.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public SecurityAppRegIntegrationTokensRecord setUpdatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_reg_integration_tokens.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAppRegIntegrationTokensRecord
     */
    public SecurityAppRegIntegrationTokensRecord() {
        super(SecurityAppRegIntegrationTokens.SECURITY_APP_REG_INTEGRATION_TOKENS);
    }

    /**
     * Create a detached, initialised SecurityAppRegIntegrationTokensRecord
     */
    public SecurityAppRegIntegrationTokensRecord(ULong id, ULong integrationId, String authCode, String state, Map requestParam, String token, String refreshToken, LocalDateTime expiresAt, Map tokenMetadata, String username, Map userMetadata, LocalDateTime createdAt, ULong createdBy, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityAppRegIntegrationTokens.SECURITY_APP_REG_INTEGRATION_TOKENS);

        setId(id);
        setIntegrationId(integrationId);
        setAuthCode(authCode);
        setState(state);
        setRequestParam(requestParam);
        setToken(token);
        setRefreshToken(refreshToken);
        setExpiresAt(expiresAt);
        setTokenMetadata(tokenMetadata);
        setUsername(username);
        setUserMetadata(userMetadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
