/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.enums.SecurityAppRegPackageLevel;
import com.fincity.security.jooq.tables.SecurityAppRegPackage;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityAppRegPackageRecord extends UpdatableRecordImpl<SecurityAppRegPackageRecord> implements Record11<ULong, ULong, String, ULong, ULong, SecurityAppRegPackageLevel, String, ULong, LocalDateTime, ULong, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_app_reg_package.ID</code>. Primary key
     */
    public SecurityAppRegPackageRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CLIENT_ID</code>.
     * Client ID
     */
    public SecurityAppRegPackageRecord setClientId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CLIENT_ID</code>.
     * Client ID
     */
    public ULong getClientId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CLIENT_TYPE</code>.
     * Client type
     */
    public SecurityAppRegPackageRecord setClientType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CLIENT_TYPE</code>.
     * Client type
     */
    public String getClientType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_app_reg_package.APP_ID</code>. App ID
     */
    public SecurityAppRegPackageRecord setAppId(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.APP_ID</code>. App ID
     */
    public ULong getAppId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_app_reg_package.PACKAGE_ID</code>.
     * Package ID
     */
    public SecurityAppRegPackageRecord setPackageId(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.PACKAGE_ID</code>.
     * Package ID
     */
    public ULong getPackageId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>security.security_app_reg_package.LEVEL</code>. Access
     * level
     */
    public SecurityAppRegPackageRecord setLevel(SecurityAppRegPackageLevel value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.LEVEL</code>. Access
     * level
     */
    public SecurityAppRegPackageLevel getLevel() {
        return (SecurityAppRegPackageLevel) get(5);
    }

    /**
     * Setter for <code>security.security_app_reg_package.BUSINESS_TYPE</code>.
     * Business type
     */
    public SecurityAppRegPackageRecord setBusinessType(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.BUSINESS_TYPE</code>.
     * Business type
     */
    public String getBusinessType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public SecurityAppRegPackageRecord setCreatedBy(ULong value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityAppRegPackageRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>security.security_app_reg_package.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public SecurityAppRegPackageRecord setUpdatedBy(ULong value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(9);
    }

    /**
     * Setter for <code>security.security_app_reg_package.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public SecurityAppRegPackageRecord setUpdatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<ULong, ULong, String, ULong, ULong, SecurityAppRegPackageLevel, String, ULong, LocalDateTime, ULong, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<ULong, ULong, String, ULong, ULong, SecurityAppRegPackageLevel, String, ULong, LocalDateTime, ULong, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.ID;
    }

    @Override
    public Field<ULong> field2() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.CLIENT_ID;
    }

    @Override
    public Field<String> field3() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.CLIENT_TYPE;
    }

    @Override
    public Field<ULong> field4() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.APP_ID;
    }

    @Override
    public Field<ULong> field5() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.PACKAGE_ID;
    }

    @Override
    public Field<SecurityAppRegPackageLevel> field6() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.LEVEL;
    }

    @Override
    public Field<String> field7() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.BUSINESS_TYPE;
    }

    @Override
    public Field<ULong> field8() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.CREATED_AT;
    }

    @Override
    public Field<ULong> field10() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE.UPDATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public ULong component2() {
        return getClientId();
    }

    @Override
    public String component3() {
        return getClientType();
    }

    @Override
    public ULong component4() {
        return getAppId();
    }

    @Override
    public ULong component5() {
        return getPackageId();
    }

    @Override
    public SecurityAppRegPackageLevel component6() {
        return getLevel();
    }

    @Override
    public String component7() {
        return getBusinessType();
    }

    @Override
    public ULong component8() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public ULong component10() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public ULong value2() {
        return getClientId();
    }

    @Override
    public String value3() {
        return getClientType();
    }

    @Override
    public ULong value4() {
        return getAppId();
    }

    @Override
    public ULong value5() {
        return getPackageId();
    }

    @Override
    public SecurityAppRegPackageLevel value6() {
        return getLevel();
    }

    @Override
    public String value7() {
        return getBusinessType();
    }

    @Override
    public ULong value8() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public ULong value10() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdatedAt();
    }

    @Override
    public SecurityAppRegPackageRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value2(ULong value) {
        setClientId(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value3(String value) {
        setClientType(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value4(ULong value) {
        setAppId(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value5(ULong value) {
        setPackageId(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value6(SecurityAppRegPackageLevel value) {
        setLevel(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value7(String value) {
        setBusinessType(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value8(ULong value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value10(ULong value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord value11(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SecurityAppRegPackageRecord values(ULong value1, ULong value2, String value3, ULong value4, ULong value5, SecurityAppRegPackageLevel value6, String value7, ULong value8, LocalDateTime value9, ULong value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAppRegPackageRecord
     */
    public SecurityAppRegPackageRecord() {
        super(SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE);
    }

    /**
     * Create a detached, initialised SecurityAppRegPackageRecord
     */
    public SecurityAppRegPackageRecord(ULong id, ULong clientId, String clientType, ULong appId, ULong packageId, SecurityAppRegPackageLevel level, String businessType, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE);

        setId(id);
        setClientId(clientId);
        setClientType(clientType);
        setAppId(appId);
        setPackageId(packageId);
        setLevel(level);
        setBusinessType(businessType);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
