/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.enums.SecurityAppActionCostActionClass;
import com.fincity.security.jooq.enums.SecurityAppActionCostStatus;
import com.fincity.security.jooq.tables.SecurityAppActionCost;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAppActionCostRecord extends UpdatableRecordImpl<SecurityAppActionCostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_app_action_cost.ID</code>. Primary key
     */
    public SecurityAppActionCostRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>security.security_app_action_cost.BILLING_CONFIG_ID</code>. Billing
     * config (app, client) that owns this rate
     */
    public SecurityAppActionCostRecord setBillingConfigId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>security.security_app_action_cost.BILLING_CONFIG_ID</code>. Billing
     * config (app, client) that owns this rate
     */
    public ULong getBillingConfigId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_app_action_cost.ACTION_KEY</code>.
     * Action key, e.g. core.email.send, security.app.rent
     */
    public SecurityAppActionCostRecord setActionKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.ACTION_KEY</code>.
     * Action key, e.g. core.email.send, security.app.rent
     */
    public String getActionKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_app_action_cost.CREDIT_COST</code>.
     * Credits charged per unit
     */
    public SecurityAppActionCostRecord setCreditCost(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.CREDIT_COST</code>.
     * Credits charged per unit
     */
    public BigDecimal getCreditCost() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>security.security_app_action_cost.ACTION_CLASS</code>.
     * Zero-balance behaviour class
     */
    public SecurityAppActionCostRecord setActionClass(SecurityAppActionCostActionClass value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.ACTION_CLASS</code>.
     * Zero-balance behaviour class
     */
    public SecurityAppActionCostActionClass getActionClass() {
        return (SecurityAppActionCostActionClass) get(4);
    }

    /**
     * Setter for <code>security.security_app_action_cost.FREE_QUOTA</code>.
     * Free units per period before charging
     */
    public SecurityAppActionCostRecord setFreeQuota(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.FREE_QUOTA</code>.
     * Free units per period before charging
     */
    public BigDecimal getFreeQuota() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>security.security_app_action_cost.STATUS</code>. Status
     */
    public SecurityAppActionCostRecord setStatus(SecurityAppActionCostStatus value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.STATUS</code>. Status
     */
    public SecurityAppActionCostStatus getStatus() {
        return (SecurityAppActionCostStatus) get(6);
    }

    /**
     * Setter for <code>security.security_app_action_cost.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public SecurityAppActionCostRecord setCreatedBy(ULong value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>security.security_app_action_cost.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityAppActionCostRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>security.security_app_action_cost.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public SecurityAppActionCostRecord setUpdatedBy(ULong value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(9);
    }

    /**
     * Setter for <code>security.security_app_action_cost.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public SecurityAppActionCostRecord setUpdatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_action_cost.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAppActionCostRecord
     */
    public SecurityAppActionCostRecord() {
        super(SecurityAppActionCost.SECURITY_APP_ACTION_COST);
    }

    /**
     * Create a detached, initialised SecurityAppActionCostRecord
     */
    public SecurityAppActionCostRecord(ULong id, ULong billingConfigId, String actionKey, BigDecimal creditCost, SecurityAppActionCostActionClass actionClass, BigDecimal freeQuota, SecurityAppActionCostStatus status, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityAppActionCost.SECURITY_APP_ACTION_COST);

        setId(id);
        setBillingConfigId(billingConfigId);
        setActionKey(actionKey);
        setCreditCost(creditCost);
        setActionClass(actionClass);
        setFreeQuota(freeQuota);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
