/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.tables.SecurityAppSso;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAppSsoRecord extends UpdatableRecordImpl<SecurityAppSsoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_app_sso.ID</code>. Primary key
     */
    public SecurityAppSsoRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_app_sso.CLIENT_ID</code>. Client ID
     */
    public SecurityAppSsoRecord setClientId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.CLIENT_ID</code>. Client ID
     */
    public ULong getClientId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_app_sso.APP_ID</code>. Application ID
     */
    public SecurityAppSsoRecord setAppId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.APP_ID</code>. Application ID
     */
    public ULong getAppId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>security.security_app_sso.TO_APP_ID</code>. TO
     * Application ID
     */
    public SecurityAppSsoRecord setToAppId(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.TO_APP_ID</code>. TO
     * Application ID
     */
    public ULong getToAppId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_app_sso.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public SecurityAppSsoRecord setCreatedBy(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>security.security_app_sso.CREATED_AT</code>. Time when
     * this row is created
     */
    public SecurityAppSsoRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.CREATED_AT</code>. Time when
     * this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>security.security_app_sso.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public SecurityAppSsoRecord setUpdatedBy(ULong value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>security.security_app_sso.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public SecurityAppSsoRecord setUpdatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_sso.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAppSsoRecord
     */
    public SecurityAppSsoRecord() {
        super(SecurityAppSso.SECURITY_APP_SSO);
    }

    /**
     * Create a detached, initialised SecurityAppSsoRecord
     */
    public SecurityAppSsoRecord(ULong id, ULong clientId, ULong appId, ULong toAppId, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityAppSso.SECURITY_APP_SSO);

        setId(id);
        setClientId(clientId);
        setAppId(appId);
        setToAppId(toAppId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
