/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables.records;


import com.fincity.security.jooq.enums.SecurityAppRegPackageLevel;
import com.fincity.security.jooq.tables.SecurityAppRegPackage;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAppRegPackageRecord extends UpdatableRecordImpl<SecurityAppRegPackageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_app_reg_package.ID</code>. Primary key
     */
    public SecurityAppRegPackageRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CLIENT_ID</code>.
     * Client ID
     */
    public SecurityAppRegPackageRecord setClientId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CLIENT_ID</code>.
     * Client ID
     */
    public ULong getClientId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CLIENT_TYPE</code>.
     * Client type
     */
    public SecurityAppRegPackageRecord setClientType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CLIENT_TYPE</code>.
     * Client type
     */
    public String getClientType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_app_reg_package.APP_ID</code>. App ID
     */
    public SecurityAppRegPackageRecord setAppId(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.APP_ID</code>. App ID
     */
    public ULong getAppId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_app_reg_package.PACKAGE_ID</code>.
     * Package ID
     */
    public SecurityAppRegPackageRecord setPackageId(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.PACKAGE_ID</code>.
     * Package ID
     */
    public ULong getPackageId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>security.security_app_reg_package.LEVEL</code>. Access
     * level
     */
    public SecurityAppRegPackageRecord setLevel(SecurityAppRegPackageLevel value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.LEVEL</code>. Access
     * level
     */
    public SecurityAppRegPackageLevel getLevel() {
        return (SecurityAppRegPackageLevel) get(5);
    }

    /**
     * Setter for <code>security.security_app_reg_package.BUSINESS_TYPE</code>.
     * Business type
     */
    public SecurityAppRegPackageRecord setBusinessType(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.BUSINESS_TYPE</code>.
     * Business type
     */
    public String getBusinessType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public SecurityAppRegPackageRecord setCreatedBy(ULong value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>security.security_app_reg_package.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityAppRegPackageRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>security.security_app_reg_package.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAppRegPackageRecord
     */
    public SecurityAppRegPackageRecord() {
        super(SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE);
    }

    /**
     * Create a detached, initialised SecurityAppRegPackageRecord
     */
    public SecurityAppRegPackageRecord(ULong id, ULong clientId, String clientType, ULong appId, ULong packageId, SecurityAppRegPackageLevel level, String businessType, ULong createdBy, LocalDateTime createdAt) {
        super(SecurityAppRegPackage.SECURITY_APP_REG_PACKAGE);

        setId(id);
        setClientId(clientId);
        setClientType(clientType);
        setAppId(appId);
        setPackageId(packageId);
        setLevel(level);
        setBusinessType(businessType);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
