package com.fincity.saas.core.integration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.ReactiveSecurityContextHolder;

import com.fincity.saas.commons.core.document.Storage;
import com.fincity.saas.commons.core.service.StorageService;
import com.fincity.saas.commons.security.jwt.ContextAuthentication;

import reactor.core.publisher.Mono;

/**
 * The override fold lives in commons-mongo and is shared by every overridable
 * document in both ui and core. The ui suite pins it for Page; this pins it for
 * a commons-core document, so a fix cannot be correct in one service and wrong
 * in the other.
 *
 * Storage matters more than most here: the draft surface gives it a parallel
 * data namespace, and its uniqueName is the physical Mongo collection name.
 */
@DisplayName("Storage override chain across client hierarchy depths")
class StorageOverrideChainIntegrationTest extends AbstractIntegrationTest {

    private static final String MID = "LZCLA";
    private static final String LEAF = "LZACP1";
    private static final String STORAGE_NAME = "testStorage";

    @Autowired
    private StorageService storageService;

    private Storage storedStorage(String clientCode, String baseClientCode, Map<String, Object> schema) {

        Storage storage = new Storage();
        storage.setName(STORAGE_NAME)
                .setAppCode(APP_CODE)
                .setClientCode(clientCode)
                .setBaseClientCode(baseClientCode)
                .setVersion(1);
        storage.setSchema(schema == null ? null : new HashMap<>(schema));
        // Generated by StorageService.create in production. Fixtures are inserted
        // raw, so it is set here: it is the physical collection name and the draft
        // surface depends on it being stable across a publish.
        storage.setUniqueName("testapp_" + clientCode.toLowerCase() + "_teststorage");
        return this.insertRaw(storage);
    }

    private static Map<String, Object> schema(Object... keyValues) {
        Map<String, Object> map = new HashMap<>();
        for (int i = 0; i < keyValues.length; i += 2)
            map.put((String) keyValues[i], keyValues[i + 1]);
        return map;
    }

    private <T> T asClient(Mono<T> mono, String clientCode) {
        ContextAuthentication ca = this.authFor(clientCode, allAuthoritiesFor("Storage"));
        return mono.contextWrite(ReactiveSecurityContextHolder.withAuthentication(ca)).block();
    }

    @Nested
    @DisplayName("CH2: base -> child")
    class TwoDeep {

        @Test
        @Timeout(30)
        @DisplayName("read merges the child over the base")
        void readMergesChildOverBase() {

            setInheritance(List.of(SYSTEM, MID));
            storedStorage(SYSTEM, null, schema("fromRoot", "r", "shared", "root"));
            Storage mid = storedStorage(MID, SYSTEM, schema("fromMid", "m", "shared", "mid"));

            Storage read = asClient(storageService.read(mid.getId()), MID);

            assertNotNull(read);
            assertEquals("r", read.getSchema().get("fromRoot"));
            assertEquals("m", read.getSchema().get("fromMid"));
            assertEquals("mid", read.getSchema().get("shared"));
        }
    }

    @Nested
    @DisplayName("CH3: base -> mid -> leaf")
    class ThreeDeep {

        @Test
        @Timeout(30)
        @DisplayName("read merges all three levels, with the most derived winning")
        void readMergesAllThreeLevels() {

            setInheritance(List.of(SYSTEM, MID, LEAF));
            storedStorage(SYSTEM, null, schema("fromRoot", "r", "sharedRootMid", "root", "sharedAll", "root"));
            storedStorage(MID, SYSTEM, schema("fromMid", "m", "sharedRootMid", "mid", "sharedAll", "mid"));
            Storage leaf = storedStorage(LEAF, MID, schema("fromLeaf", "l", "sharedAll", "leaf"));

            Storage read = asClient(storageService.read(leaf.getId()), LEAF);

            assertNotNull(read);
            Map<String, Object> s = read.getSchema();

            assertEquals("r", s.get("fromRoot"), "a root-only key must survive a three-level merge");
            assertEquals("m", s.get("fromMid"));
            assertEquals("l", s.get("fromLeaf"));
            assertEquals("mid", s.get("sharedRootMid"), "mid must win over root");
            assertEquals("leaf", s.get("sharedAll"), "leaf must win over both");
        }

        @Test
        @Timeout(30)
        @DisplayName("reading does not collapse the leaf's stored delta")
        void readDoesNotCollapseStoredDelta() {

            setInheritance(List.of(SYSTEM, MID, LEAF));
            storedStorage(SYSTEM, null, schema("fromRoot", "r"));
            storedStorage(MID, SYSTEM, schema("fromMid", "m"));
            Storage leaf = storedStorage(LEAF, MID, schema("fromLeaf", "l"));

            assertNotNull(asClient(storageService.read(leaf.getId()), LEAF));

            Storage stored = mongoTemplate.findById(leaf.getId(), Storage.class).block();
            assertNotNull(stored);
            assertEquals(1, stored.getSchema().size(),
                    "the stored leaf must still hold only its own delta after a read");
            assertEquals("l", stored.getSchema().get("fromLeaf"));
        }

        @Test
        @Timeout(30)
        @DisplayName("uniqueName is not inherited from the base")
        void uniqueNameIsNotInherited() {

            setInheritance(List.of(SYSTEM, MID, LEAF));
            storedStorage(SYSTEM, null, schema("fromRoot", "r"));
            storedStorage(MID, SYSTEM, schema("fromMid", "m"));
            Storage leaf = storedStorage(LEAF, MID, schema("fromLeaf", "l"));

            Storage read = asClient(storageService.read(leaf.getId()), LEAF);

            assertNotNull(read);
            // The physical collection is per stored document. If a merge ever started
            // pulling uniqueName down from the base, two clients would silently share
            // one collection.
            assertEquals("testapp_lzacp1_teststorage", read.getUniqueName());
        }
    }
}
