package com.fincity.saas.core.enums;

public enum StorageTriggerType {

    BEFORE_CREATE,
    AFTER_CREATE,
    BEFORE_UPDATE,
    AFTER_UPDATE,
    BEFORE_DELETE,
    AFTER_DELETE,
    BEFORE_UPDATE_STORAGE,
    AFTER_UPDATE_STORAGE,
    BEFORE_DELETE_STORAGE,
    AFTER_DELETE_STORAGE;
}
