ALTER TABLE `message`.`message_exotel_calls`
    MODIFY COLUMN `EXOTEL_CALL_STATUS` ENUM ('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'BUSY', 'NO_ANSWER', 'CANCELLED') DEFAULT 'IN_PROGRESS' NOT NULL COMMENT 'Status of the call.';
