ALTER TABLE `message`.`message_messages`
    DROP FOREIGN KEY `FK2_MESSAGES_WHATSAPP_TEMPLATES_ID`;

ALTER TABLE `message`.`message_messages`
    DROP COLUMN `FROM_DIAL_CODE`,
    DROP COLUMN `FROM`,
    DROP COLUMN `TO_DIAL_CODE`,
    DROP COLUMN `TO`,
    DROP COLUMN `MESSAGE_STATUS`,
    DROP COLUMN `SENT_TIME`,
    DROP COLUMN `DELIVERED_TIME`,
    DROP COLUMN `READ_TIME`,
    DROP COLUMN `WHATSAPP_TEMPLATE_ID`,
    DROP COLUMN `METADATA`;
