/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.notification.jooq.tables.records;


import com.fincity.saas.notification.jooq.tables.NotificationType;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationTypeRecord extends UpdatableRecordImpl<NotificationTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notification.notification_type.ID</code>. Primary key
     */
    public NotificationTypeRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>notification.notification_type.CLIENT_ID</code>.
     * Identifier for the client. References security_client table
     */
    public NotificationTypeRecord setClientId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.CLIENT_ID</code>.
     * Identifier for the client. References security_client table
     */
    public ULong getClientId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>notification.notification_type.APP_ID</code>. Identifier
     * for the application. References security_app table
     */
    public NotificationTypeRecord setAppId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.APP_ID</code>. Identifier
     * for the application. References security_app table
     */
    public ULong getAppId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>notification.notification_type.CODE</code>. Code
     */
    public NotificationTypeRecord setCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.CODE</code>. Code
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notification.notification_type.NAME</code>. Notification
     * type name
     */
    public NotificationTypeRecord setName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.NAME</code>. Notification
     * type name
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>notification.notification_type.DESCRIPTION</code>.
     * Description of notification type
     */
    public NotificationTypeRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.DESCRIPTION</code>.
     * Description of notification type
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>notification.notification_type.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public NotificationTypeRecord setCreatedBy(ULong value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>notification.notification_type.CREATED_AT</code>. Time
     * when this row is created
     */
    public NotificationTypeRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.CREATED_AT</code>. Time
     * when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>notification.notification_type.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public NotificationTypeRecord setUpdatedBy(ULong value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>notification.notification_type.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public NotificationTypeRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_type.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationTypeRecord
     */
    public NotificationTypeRecord() {
        super(NotificationType.NOTIFICATION_TYPE);
    }

    /**
     * Create a detached, initialised NotificationTypeRecord
     */
    public NotificationTypeRecord(ULong id, ULong clientId, ULong appId, String code, String name, String description, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(NotificationType.NOTIFICATION_TYPE);

        setId(id);
        setClientId(clientId);
        setAppId(appId);
        setCode(code);
        setName(name);
        setDescription(description);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
