/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.notification.jooq.tables.records;


import com.fincity.saas.notification.enums.NotificationChannelType;
import com.fincity.saas.notification.jooq.tables.NotificationUserChannelPref;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationUserChannelPrefRecord extends UpdatableRecordImpl<NotificationUserChannelPrefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notification.notification_user_channel_pref.ID</code>.
     * Primary key
     */
    public NotificationUserChannelPrefRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_user_channel_pref.ID</code>.
     * Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.APP_ID</code>.
     * Identifier for the application. References security_app table
     */
    public NotificationUserChannelPrefRecord setAppId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.APP_ID</code>.
     * Identifier for the application. References security_app table
     */
    public ULong getAppId() {
        return (ULong) get(1);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.USER_ID</code>.
     * Identifier for the user. References security_user table
     */
    public NotificationUserChannelPrefRecord setUserId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.USER_ID</code>.
     * Identifier for the user. References security_user table
     */
    public ULong getUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>notification.notification_user_channel_pref.CODE</code>.
     * Unique Code to identify this row
     */
    public NotificationUserChannelPrefRecord setCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>notification.notification_user_channel_pref.CODE</code>.
     * Unique Code to identify this row
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.CHANNEL_TYPE</code>.
     * Notification app preferences
     */
    public NotificationUserChannelPrefRecord setChannelType(NotificationChannelType value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.CHANNEL_TYPE</code>.
     * Notification app preferences
     */
    public NotificationChannelType getChannelType() {
        return (NotificationChannelType) get(4);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.ENABLED</code>.
     * Notification name enabled or not
     */
    public NotificationUserChannelPrefRecord setEnabled(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.ENABLED</code>.
     * Notification name enabled or not
     */
    public Byte getEnabled() {
        return (Byte) get(5);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public NotificationUserChannelPrefRecord setCreatedBy(ULong value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(6);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.CREATED_AT</code>. Time
     * when this row is created
     */
    public NotificationUserChannelPrefRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.CREATED_AT</code>. Time
     * when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public NotificationUserChannelPrefRecord setUpdatedBy(ULong value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(8);
    }

    /**
     * Setter for
     * <code>notification.notification_user_channel_pref.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public NotificationUserChannelPrefRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>notification.notification_user_channel_pref.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationUserChannelPrefRecord
     */
    public NotificationUserChannelPrefRecord() {
        super(NotificationUserChannelPref.NOTIFICATION_USER_CHANNEL_PREF);
    }

    /**
     * Create a detached, initialised NotificationUserChannelPrefRecord
     */
    public NotificationUserChannelPrefRecord(ULong id, ULong appId, ULong userId, String code, NotificationChannelType channelType, Byte enabled, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(NotificationUserChannelPref.NOTIFICATION_USER_CHANNEL_PREF);

        setId(id);
        setAppId(appId);
        setUserId(userId);
        setCode(code);
        setChannelType(channelType);
        setEnabled(enabled);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
