/*
 * This file is generated by jOOQ.
 */
package com.fincity.sass.worker.jooq.tables.records;


import com.fincity.sass.worker.enums.SchedulerStatus;
import com.fincity.sass.worker.jooq.tables.WorkerSchedulers;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkerSchedulersRecord extends UpdatableRecordImpl<WorkerSchedulersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>worker.worker_schedulers.ID</code>. Primary key, unique
     * identifier for each scheduler
     */
    public WorkerSchedulersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.ID</code>. Primary key, unique
     * identifier for each scheduler
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>worker.worker_schedulers.NAME</code>. name of the
     * scheduler
     */
    public WorkerSchedulersRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.NAME</code>. name of the
     * scheduler
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>worker.worker_schedulers.SCHEDULER_STATUS</code>.
     * Scheduler running flag.
     */
    public WorkerSchedulersRecord setSchedulerStatus(SchedulerStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.SCHEDULER_STATUS</code>.
     * Scheduler running flag.
     */
    public SchedulerStatus getSchedulerStatus() {
        return (SchedulerStatus) get(2);
    }

    /**
     * Setter for <code>worker.worker_schedulers.INSTANCE_ID</code>. scheduler
     * instance id
     */
    public WorkerSchedulersRecord setInstanceId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.INSTANCE_ID</code>. scheduler
     * instance id
     */
    public String getInstanceId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>worker.worker_schedulers.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public WorkerSchedulersRecord setCreatedBy(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>worker.worker_schedulers.CREATED_AT</code>. Time when
     * this row is created
     */
    public WorkerSchedulersRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.CREATED_AT</code>. Time when
     * this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>worker.worker_schedulers.UPDATED_BY</code>. ID of the
     * user who last updated this row
     */
    public WorkerSchedulersRecord setUpdatedBy(ULong value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.UPDATED_BY</code>. ID of the
     * user who last updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>worker.worker_schedulers.UPDATED_AT</code>. Time when
     * this row is last updated
     */
    public WorkerSchedulersRecord setUpdatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>worker.worker_schedulers.UPDATED_AT</code>. Time when
     * this row is last updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerSchedulersRecord
     */
    public WorkerSchedulersRecord() {
        super(WorkerSchedulers.WORKER_SCHEDULERS);
    }

    /**
     * Create a detached, initialised WorkerSchedulersRecord
     */
    public WorkerSchedulersRecord(ULong id, String name, SchedulerStatus schedulerStatus, String instanceId, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(WorkerSchedulers.WORKER_SCHEDULERS);

        setId(id);
        setName(name);
        setSchedulerStatus(schedulerStatus);
        setInstanceId(instanceId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
