/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.notification.jooq;


import com.fincity.saas.notification.jooq.tables.NotificationConnection;
import com.fincity.saas.notification.jooq.tables.NotificationNotification;
import com.fincity.saas.notification.jooq.tables.NotificationTemplate;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in notification.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NOTIFICATION_CONNECTION_IDX1_CONNECTION_CODE_CLIENT_ID_APP_ID = Internal.createIndex(DSL.name("IDX1_CONNECTION_CODE_CLIENT_ID_APP_ID"), NotificationConnection.NOTIFICATION_CONNECTION, new OrderField[] { NotificationConnection.NOTIFICATION_CONNECTION.CODE, NotificationConnection.NOTIFICATION_CONNECTION.CLIENT_ID, NotificationConnection.NOTIFICATION_CONNECTION.APP_ID }, false);
    public static final Index NOTIFICATION_NOTIFICATION_IDX1_NOTIFICATION_CLIENT_ID_APP_ID_NOTI_TYPE = Internal.createIndex(DSL.name("IDX1_NOTIFICATION_CLIENT_ID_APP_ID_NOTI_TYPE"), NotificationNotification.NOTIFICATION_NOTIFICATION, new OrderField[] { NotificationNotification.NOTIFICATION_NOTIFICATION.CLIENT_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.APP_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.NOTIFICATION_TYPE }, false);
    public static final Index NOTIFICATION_NOTIFICATION_IDX1_NOTIFICATION_CODE_NOTI_TYPE = Internal.createIndex(DSL.name("IDX1_NOTIFICATION_CODE_NOTI_TYPE"), NotificationNotification.NOTIFICATION_NOTIFICATION, new OrderField[] { NotificationNotification.NOTIFICATION_NOTIFICATION.CODE, NotificationNotification.NOTIFICATION_NOTIFICATION.NOTIFICATION_TYPE }, false);
    public static final Index NOTIFICATION_TEMPLATE_IDX1_TEMPLATE_CODE_CLIENT_ID_APP_ID = Internal.createIndex(DSL.name("IDX1_TEMPLATE_CODE_CLIENT_ID_APP_ID"), NotificationTemplate.NOTIFICATION_TEMPLATE, new OrderField[] { NotificationTemplate.NOTIFICATION_TEMPLATE.CODE, NotificationTemplate.NOTIFICATION_TEMPLATE.CLIENT_ID, NotificationTemplate.NOTIFICATION_TEMPLATE.APP_ID }, false);
    public static final Index NOTIFICATION_CONNECTION_IDX2_CONNECTION_CLIENT_ID_APP_ID = Internal.createIndex(DSL.name("IDX2_CONNECTION_CLIENT_ID_APP_ID"), NotificationConnection.NOTIFICATION_CONNECTION, new OrderField[] { NotificationConnection.NOTIFICATION_CONNECTION.CLIENT_ID, NotificationConnection.NOTIFICATION_CONNECTION.APP_ID }, false);
    public static final Index NOTIFICATION_NOTIFICATION_IDX2_NOTIFICATION_APP_ID_USER_ID_NOTI_TYPE = Internal.createIndex(DSL.name("IDX2_NOTIFICATION_APP_ID_USER_ID_NOTI_TYPE"), NotificationNotification.NOTIFICATION_NOTIFICATION, new OrderField[] { NotificationNotification.NOTIFICATION_NOTIFICATION.APP_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.USER_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.NOTIFICATION_TYPE }, false);
    public static final Index NOTIFICATION_TEMPLATE_IDX2_TEMPLATE_CLIENT_ID_APP_ID = Internal.createIndex(DSL.name("IDX2_TEMPLATE_CLIENT_ID_APP_ID"), NotificationTemplate.NOTIFICATION_TEMPLATE, new OrderField[] { NotificationTemplate.NOTIFICATION_TEMPLATE.CLIENT_ID, NotificationTemplate.NOTIFICATION_TEMPLATE.APP_ID }, false);
    public static final Index NOTIFICATION_NOTIFICATION_IDX3_NOTIFICATION_CLIENT_ID_APP_ID_USER_ID_NOTI_TYPE = Internal.createIndex(DSL.name("IDX3_NOTIFICATION_CLIENT_ID_APP_ID_USER_ID_NOTI_TYPE"), NotificationNotification.NOTIFICATION_NOTIFICATION, new OrderField[] { NotificationNotification.NOTIFICATION_NOTIFICATION.CLIENT_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.APP_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.USER_ID, NotificationNotification.NOTIFICATION_NOTIFICATION.NOTIFICATION_TYPE }, false);
}
