/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.notification.jooq;

import com.fincity.saas.notification.jooq.tables.NotificationInAppNotifications;
import com.fincity.saas.notification.jooq.tables.NotificationSentNotifications;
import com.fincity.saas.notification.jooq.tables.NotificationUserPreferences;

/**
 * Convenience access to all tables in notification.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>notification.notification_in_app_notifications</code>.
     */
    public static final NotificationInAppNotifications NOTIFICATION_IN_APP_NOTIFICATIONS =
            NotificationInAppNotifications.NOTIFICATION_IN_APP_NOTIFICATIONS;

    /**
     * The table <code>notification.notification_sent_notifications</code>.
     */
    public static final NotificationSentNotifications NOTIFICATION_SENT_NOTIFICATIONS =
            NotificationSentNotifications.NOTIFICATION_SENT_NOTIFICATIONS;

    /**
     * The table <code>notification.notification_user_preferences</code>.
     */
    public static final NotificationUserPreferences NOTIFICATION_USER_PREFERENCES =
            NotificationUserPreferences.NOTIFICATION_USER_PREFERENCES;
}
