/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.notification.jooq;


import com.fincity.saas.notification.jooq.tables.NotificationType;


/**
 * Convenience access to all tables in notification.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>notification.notification_type</code>.
     */
    public static final NotificationType NOTIFICATION_TYPE = NotificationType.NOTIFICATION_TYPE;
}
