/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.notification.jooq;


import com.fincity.saas.notification.jooq.tables.NotificationUserChannelPref;
import com.fincity.saas.notification.jooq.tables.NotificationUserNotificationPref;


/**
 * Convenience access to all tables in notification.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>notification.notification_user_channel_pref</code>.
     */
    public static final NotificationUserChannelPref NOTIFICATION_USER_CHANNEL_PREF = NotificationUserChannelPref.NOTIFICATION_USER_CHANNEL_PREF;

    /**
     * The table <code>notification.notification_user_notification_pref</code>.
     */
    public static final NotificationUserNotificationPref NOTIFICATION_USER_NOTIFICATION_PREF = NotificationUserNotificationPref.NOTIFICATION_USER_NOTIFICATION_PREF;
}
