CREATE SCHEMA NOTIFICATION;

CREATE TABLE NOTIFICATION.NOTIFICATION_TYPE
(
    ID          BIGSERIAL    NOT NULL,
    CLIENT_ID   BIGINT       NOT NULL CHECK ( CLIENT_ID > 0 ),
    APP_ID      BIGINT       NOT NULL CHECK ( APP_ID > 0 ),
    CODE        CHAR(36)     NOT NULL,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(512),
    CREATED_BY  BIGINT                   DEFAULT NULL CHECK (CREATED_BY > 0 ),
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  BIGINT                   DEFAULT NULL CHECK ( UPDATED_BY > 0 ),
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT UK1_NOTIFICATION_TYPE_CODE UNIQUE (CODE),
    CONSTRAINT UK2_NOTIFICATION_TYPE_CLIENT_ID_APP_ID_NAME UNIQUE (CLIENT_ID, APP_ID, NAME)
);

