use notification;

ALTER TABLE `notification`.`notification_inapp`
ADD COLUMN `NOTIFICATION_CATEGORY` VARCHAR(256) NOT NULL DEFAULT 'Default' COMMENT 'Notification category' AFTER `NOTIFICATION_TYPE`,
ADD COLUMN `URL` TEXT DEFAULT NULL COMMENT 'Notification URL' AFTER `NOTIFICATION_CATEGORY`;
