/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.entity.processor.jooq;


import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorActivities;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorCampaigns;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorComplexRules;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorNotes;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorOwners;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorPartners;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorProductComms;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorProductStageRules;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorProductTemplateRules;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorProductTemplates;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorProducts;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorSimpleComplexRuleRelations;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorSimpleRules;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorStages;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorTaskTypes;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorTasks;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorTickets;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in entity_processor.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ENTITY_PROCESSOR_ACTIVITIES_IDX0_ACTIVITIES_AC_CC = Internal.createIndex(DSL.name("IDX0_ACTIVITIES_AC_CC"), EntityProcessorActivities.ENTITY_PROCESSOR_ACTIVITIES, new OrderField[] { EntityProcessorActivities.ENTITY_PROCESSOR_ACTIVITIES.APP_CODE, EntityProcessorActivities.ENTITY_PROCESSOR_ACTIVITIES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_CAMPAIGNS_IDX0_CAMPAIGNS_AC_CC = Internal.createIndex(DSL.name("IDX0_CAMPAIGNS_AC_CC"), EntityProcessorCampaigns.ENTITY_PROCESSOR_CAMPAIGNS, new OrderField[] { EntityProcessorCampaigns.ENTITY_PROCESSOR_CAMPAIGNS.APP_CODE, EntityProcessorCampaigns.ENTITY_PROCESSOR_CAMPAIGNS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_COMPLEX_RULES_IDX0_COMPLEX_RULES_AC_CC = Internal.createIndex(DSL.name("IDX0_COMPLEX_RULES_AC_CC"), EntityProcessorComplexRules.ENTITY_PROCESSOR_COMPLEX_RULES, new OrderField[] { EntityProcessorComplexRules.ENTITY_PROCESSOR_COMPLEX_RULES.APP_CODE, EntityProcessorComplexRules.ENTITY_PROCESSOR_COMPLEX_RULES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_NOTES_IDX0_NOTES_AC_CC = Internal.createIndex(DSL.name("IDX0_NOTES_AC_CC"), EntityProcessorNotes.ENTITY_PROCESSOR_NOTES, new OrderField[] { EntityProcessorNotes.ENTITY_PROCESSOR_NOTES.APP_CODE, EntityProcessorNotes.ENTITY_PROCESSOR_NOTES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_OWNERS_IDX0_OWNERS_AC_CC = Internal.createIndex(DSL.name("IDX0_OWNERS_AC_CC"), EntityProcessorOwners.ENTITY_PROCESSOR_OWNERS, new OrderField[] { EntityProcessorOwners.ENTITY_PROCESSOR_OWNERS.APP_CODE, EntityProcessorOwners.ENTITY_PROCESSOR_OWNERS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_PARTNERS_IDX0_PARTNERS_AC_CC = Internal.createIndex(DSL.name("IDX0_PARTNERS_AC_CC"), EntityProcessorPartners.ENTITY_PROCESSOR_PARTNERS, new OrderField[] { EntityProcessorPartners.ENTITY_PROCESSOR_PARTNERS.APP_CODE, EntityProcessorPartners.ENTITY_PROCESSOR_PARTNERS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_PRODUCT_COMMS_IDX0_PRODUCT_COMMS_AC_CC = Internal.createIndex(DSL.name("IDX0_PRODUCT_COMMS_AC_CC"), EntityProcessorProductComms.ENTITY_PROCESSOR_PRODUCT_COMMS, new OrderField[] { EntityProcessorProductComms.ENTITY_PROCESSOR_PRODUCT_COMMS.APP_CODE, EntityProcessorProductComms.ENTITY_PROCESSOR_PRODUCT_COMMS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_PRODUCT_STAGE_RULES_IDX0_PRODUCT_STAGE_RULES_AC_CC = Internal.createIndex(DSL.name("IDX0_PRODUCT_STAGE_RULES_AC_CC"), EntityProcessorProductStageRules.ENTITY_PROCESSOR_PRODUCT_STAGE_RULES, new OrderField[] { EntityProcessorProductStageRules.ENTITY_PROCESSOR_PRODUCT_STAGE_RULES.APP_CODE, EntityProcessorProductStageRules.ENTITY_PROCESSOR_PRODUCT_STAGE_RULES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_PRODUCT_TEMPLATE_RULES_IDX0_PRODUCT_TEMPLATE_RULES_AC_CC = Internal.createIndex(DSL.name("IDX0_PRODUCT_TEMPLATE_RULES_AC_CC"), EntityProcessorProductTemplateRules.ENTITY_PROCESSOR_PRODUCT_TEMPLATE_RULES, new OrderField[] { EntityProcessorProductTemplateRules.ENTITY_PROCESSOR_PRODUCT_TEMPLATE_RULES.APP_CODE, EntityProcessorProductTemplateRules.ENTITY_PROCESSOR_PRODUCT_TEMPLATE_RULES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_PRODUCT_TEMPLATES_IDX0_PRODUCT_TEMPLATES_AC_CC = Internal.createIndex(DSL.name("IDX0_PRODUCT_TEMPLATES_AC_CC"), EntityProcessorProductTemplates.ENTITY_PROCESSOR_PRODUCT_TEMPLATES, new OrderField[] { EntityProcessorProductTemplates.ENTITY_PROCESSOR_PRODUCT_TEMPLATES.APP_CODE, EntityProcessorProductTemplates.ENTITY_PROCESSOR_PRODUCT_TEMPLATES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_PRODUCTS_IDX0_PRODUCTS_AC_CC = Internal.createIndex(DSL.name("IDX0_PRODUCTS_AC_CC"), EntityProcessorProducts.ENTITY_PROCESSOR_PRODUCTS, new OrderField[] { EntityProcessorProducts.ENTITY_PROCESSOR_PRODUCTS.APP_CODE, EntityProcessorProducts.ENTITY_PROCESSOR_PRODUCTS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_SIMPLE_COMPLEX_RULE_RELATIONS_IDX0_SIMPLE_COMPLEX_RULE_RELATIONS_AC_CC = Internal.createIndex(DSL.name("IDX0_SIMPLE_COMPLEX_RULE_RELATIONS_AC_CC"), EntityProcessorSimpleComplexRuleRelations.ENTITY_PROCESSOR_SIMPLE_COMPLEX_RULE_RELATIONS, new OrderField[] { EntityProcessorSimpleComplexRuleRelations.ENTITY_PROCESSOR_SIMPLE_COMPLEX_RULE_RELATIONS.APP_CODE, EntityProcessorSimpleComplexRuleRelations.ENTITY_PROCESSOR_SIMPLE_COMPLEX_RULE_RELATIONS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_SIMPLE_RULES_IDX0_SIMPLE_RULES_AC_CC = Internal.createIndex(DSL.name("IDX0_SIMPLE_RULES_AC_CC"), EntityProcessorSimpleRules.ENTITY_PROCESSOR_SIMPLE_RULES, new OrderField[] { EntityProcessorSimpleRules.ENTITY_PROCESSOR_SIMPLE_RULES.APP_CODE, EntityProcessorSimpleRules.ENTITY_PROCESSOR_SIMPLE_RULES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_STAGES_IDX0_STAGES_AC_CC = Internal.createIndex(DSL.name("IDX0_STAGES_AC_CC"), EntityProcessorStages.ENTITY_PROCESSOR_STAGES, new OrderField[] { EntityProcessorStages.ENTITY_PROCESSOR_STAGES.APP_CODE, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_TASK_TYPES_IDX0_TASK_TYPES_AC_CC = Internal.createIndex(DSL.name("IDX0_TASK_TYPES_AC_CC"), EntityProcessorTaskTypes.ENTITY_PROCESSOR_TASK_TYPES, new OrderField[] { EntityProcessorTaskTypes.ENTITY_PROCESSOR_TASK_TYPES.APP_CODE, EntityProcessorTaskTypes.ENTITY_PROCESSOR_TASK_TYPES.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_TASKS_IDX0_TASKS_AC_CC = Internal.createIndex(DSL.name("IDX0_TASKS_AC_CC"), EntityProcessorTasks.ENTITY_PROCESSOR_TASKS, new OrderField[] { EntityProcessorTasks.ENTITY_PROCESSOR_TASKS.APP_CODE, EntityProcessorTasks.ENTITY_PROCESSOR_TASKS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_TICKETS_IDX0_TICKETS_AC_CC = Internal.createIndex(DSL.name("IDX0_TICKETS_AC_CC"), EntityProcessorTickets.ENTITY_PROCESSOR_TICKETS, new OrderField[] { EntityProcessorTickets.ENTITY_PROCESSOR_TICKETS.APP_CODE, EntityProcessorTickets.ENTITY_PROCESSOR_TICKETS.CLIENT_CODE }, false);
    public static final Index ENTITY_PROCESSOR_STAGES_IDX1_STAGE_NAME = Internal.createIndex(DSL.name("IDX1_STAGE_NAME"), EntityProcessorStages.ENTITY_PROCESSOR_STAGES, new OrderField[] { EntityProcessorStages.ENTITY_PROCESSOR_STAGES.APP_CODE, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.CLIENT_CODE, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.PRODUCT_TEMPLATE_ID, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.NAME }, false);
    public static final Index ENTITY_PROCESSOR_STAGES_IDX2_STAGE_NAME_PLATFORM = Internal.createIndex(DSL.name("IDX2_STAGE_NAME_PLATFORM"), EntityProcessorStages.ENTITY_PROCESSOR_STAGES, new OrderField[] { EntityProcessorStages.ENTITY_PROCESSOR_STAGES.APP_CODE, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.CLIENT_CODE, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.PRODUCT_TEMPLATE_ID, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.NAME, EntityProcessorStages.ENTITY_PROCESSOR_STAGES.PLATFORM }, false);
}
