/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.entity.processor.jooq.tables;


import com.fincity.saas.entity.processor.enums.Platform;
import com.fincity.saas.entity.processor.jooq.EntityProcessor;
import com.fincity.saas.entity.processor.jooq.Indexes;
import com.fincity.saas.entity.processor.jooq.Keys;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorCampaigns.EntityProcessorCampaignsPath;
import com.fincity.saas.entity.processor.jooq.tables.records.EntityProcessorCampaignMetricsRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EntityProcessorCampaignMetrics extends TableImpl<EntityProcessorCampaignMetricsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>entity_processor.entity_processor_campaign_metrics</code>
     */
    public static final EntityProcessorCampaignMetrics ENTITY_PROCESSOR_CAMPAIGN_METRICS = new EntityProcessorCampaignMetrics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityProcessorCampaignMetricsRecord> getRecordType() {
        return EntityProcessorCampaignMetricsRecord.class;
    }

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.ID</code>.
     * Primary key.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.CODE</code>.
     * Unique Code to identify this row.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.CHAR(22).nullable(false), this, "Unique Code to identify this row.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.APP_CODE</code>.
     * App Code.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, String> APP_CODE = createField(DSL.name("APP_CODE"), SQLDataType.CHAR(64).nullable(false), this, "App Code.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.CLIENT_CODE</code>.
     * Client Code.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, String> CLIENT_CODE = createField(DSL.name("CLIENT_CODE"), SQLDataType.CHAR(8).nullable(false), this, "Client Code.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.CAMPAIGN_ID</code>.
     * FK to entity_processor_campaigns.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, ULong> CAMPAIGN_ID = createField(DSL.name("CAMPAIGN_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to entity_processor_campaigns.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.ADSET_ID</code>.
     * FK to entity_processor_adsets. NULL for campaign-level.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, ULong> ADSET_ID = createField(DSL.name("ADSET_ID"), SQLDataType.BIGINTUNSIGNED, this, "FK to entity_processor_adsets. NULL for campaign-level.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.AD_ID</code>. FK
     * to entity_processor_ads. NULL for adset/campaign-level.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, ULong> AD_ID = createField(DSL.name("AD_ID"), SQLDataType.BIGINTUNSIGNED, this, "FK to entity_processor_ads. NULL for adset/campaign-level.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.METRIC_DATE</code>.
     * The day these metrics are for.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, LocalDate> METRIC_DATE = createField(DSL.name("METRIC_DATE"), SQLDataType.LOCALDATE.nullable(false), this, "The day these metrics are for.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.IMPRESSIONS</code>.
     * Number of impressions.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, Long> IMPRESSIONS = createField(DSL.name("IMPRESSIONS"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "Number of impressions.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.CLICKS</code>.
     * Number of clicks.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, Long> CLICKS = createField(DSL.name("CLICKS"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "Number of clicks.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.SPEND</code>.
     * Spend in platform currency.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, BigDecimal> SPEND = createField(DSL.name("SPEND"), SQLDataType.DECIMAL(14, 4).nullable(false).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "Spend in platform currency.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.PLATFORM_WL</code>.
     * Website Leads count.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, Long> PLATFORM_WL = createField(DSL.name("PLATFORM_WL"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "Website Leads count.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.PLATFORM_FL</code>.
     * Form Leads count.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, Long> PLATFORM_FL = createField(DSL.name("PLATFORM_FL"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "Form Leads count.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.CURRENCY</code>.
     * Currency code.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, String> CURRENCY = createField(DSL.name("CURRENCY"), SQLDataType.CHAR(3).defaultValue(DSL.inline("INR", SQLDataType.CHAR)), this, "Currency code.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.PLATFORM</code>.
     * Ad platform.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, Platform> PLATFORM = createField(DSL.name("PLATFORM"), SQLDataType.VARCHAR(10).nullable(false), this, "Ad platform.", new EnumConverter<String, Platform>(String.class, Platform.class));

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.CREATED_AT</code>.
     * Time when this row is created.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created.");

    /**
     * The column
     * <code>entity_processor.entity_processor_campaign_metrics.UPDATED_AT</code>.
     * Time when this row is updated.
     */
    public final TableField<EntityProcessorCampaignMetricsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated.");

    private EntityProcessorCampaignMetrics(Name alias, Table<EntityProcessorCampaignMetricsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EntityProcessorCampaignMetrics(Name alias, Table<EntityProcessorCampaignMetricsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>entity_processor.entity_processor_campaign_metrics</code> table
     * reference
     */
    public EntityProcessorCampaignMetrics(String alias) {
        this(DSL.name(alias), ENTITY_PROCESSOR_CAMPAIGN_METRICS);
    }

    /**
     * Create an aliased
     * <code>entity_processor.entity_processor_campaign_metrics</code> table
     * reference
     */
    public EntityProcessorCampaignMetrics(Name alias) {
        this(alias, ENTITY_PROCESSOR_CAMPAIGN_METRICS);
    }

    /**
     * Create a <code>entity_processor.entity_processor_campaign_metrics</code>
     * table reference
     */
    public EntityProcessorCampaignMetrics() {
        this(DSL.name("entity_processor_campaign_metrics"), null);
    }

    public <O extends Record> EntityProcessorCampaignMetrics(Table<O> path, ForeignKey<O, EntityProcessorCampaignMetricsRecord> childPath, InverseForeignKey<O, EntityProcessorCampaignMetricsRecord> parentPath) {
        super(path, childPath, parentPath, ENTITY_PROCESSOR_CAMPAIGN_METRICS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EntityProcessorCampaignMetricsPath extends EntityProcessorCampaignMetrics implements Path<EntityProcessorCampaignMetricsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EntityProcessorCampaignMetricsPath(Table<O> path, ForeignKey<O, EntityProcessorCampaignMetricsRecord> childPath, InverseForeignKey<O, EntityProcessorCampaignMetricsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EntityProcessorCampaignMetricsPath(Name alias, Table<EntityProcessorCampaignMetricsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EntityProcessorCampaignMetricsPath as(String alias) {
            return new EntityProcessorCampaignMetricsPath(DSL.name(alias), this);
        }

        @Override
        public EntityProcessorCampaignMetricsPath as(Name alias) {
            return new EntityProcessorCampaignMetricsPath(alias, this);
        }

        @Override
        public EntityProcessorCampaignMetricsPath as(Table<?> alias) {
            return new EntityProcessorCampaignMetricsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : EntityProcessor.ENTITY_PROCESSOR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ENTITY_PROCESSOR_CAMPAIGN_METRICS_IDX1_METRICS_DATE, Indexes.ENTITY_PROCESSOR_CAMPAIGN_METRICS_IDX2_METRICS_CAMPAIGN);
    }

    @Override
    public Identity<EntityProcessorCampaignMetricsRecord, ULong> getIdentity() {
        return (Identity<EntityProcessorCampaignMetricsRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<EntityProcessorCampaignMetricsRecord> getPrimaryKey() {
        return Keys.KEY_ENTITY_PROCESSOR_CAMPAIGN_METRICS_PRIMARY;
    }

    @Override
    public List<UniqueKey<EntityProcessorCampaignMetricsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ENTITY_PROCESSOR_CAMPAIGN_METRICS_UK1_METRICS_CODE, Keys.KEY_ENTITY_PROCESSOR_CAMPAIGN_METRICS_UK2_METRICS_COMPOSITE);
    }

    @Override
    public List<ForeignKey<EntityProcessorCampaignMetricsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK1_METRICS_CAMPAIGN);
    }

    private transient EntityProcessorCampaignsPath _entityProcessorCampaigns;

    /**
     * Get the implicit join path to the
     * <code>entity_processor.entity_processor_campaigns</code> table.
     */
    public EntityProcessorCampaignsPath entityProcessorCampaigns() {
        if (_entityProcessorCampaigns == null)
            _entityProcessorCampaigns = new EntityProcessorCampaignsPath(this, Keys.FK1_METRICS_CAMPAIGN, null);

        return _entityProcessorCampaigns;
    }

    @Override
    public EntityProcessorCampaignMetrics as(String alias) {
        return new EntityProcessorCampaignMetrics(DSL.name(alias), this);
    }

    @Override
    public EntityProcessorCampaignMetrics as(Name alias) {
        return new EntityProcessorCampaignMetrics(alias, this);
    }

    @Override
    public EntityProcessorCampaignMetrics as(Table<?> alias) {
        return new EntityProcessorCampaignMetrics(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorCampaignMetrics rename(String name) {
        return new EntityProcessorCampaignMetrics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorCampaignMetrics rename(Name name) {
        return new EntityProcessorCampaignMetrics(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorCampaignMetrics rename(Table<?> name) {
        return new EntityProcessorCampaignMetrics(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorCampaignMetrics where(Condition condition) {
        return new EntityProcessorCampaignMetrics(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorCampaignMetrics where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorCampaignMetrics where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorCampaignMetrics where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorCampaignMetrics where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorCampaignMetrics where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorCampaignMetrics where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorCampaignMetrics where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorCampaignMetrics whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorCampaignMetrics whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
