/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.entity.processor.jooq.tables;


import com.fincity.saas.commons.jooq.convertor.jooq.converters.JSONtoClassConverter;
import com.fincity.saas.entity.processor.enums.ActivityAction;
import com.fincity.saas.entity.processor.enums.EntitySeries;
import com.fincity.saas.entity.processor.jooq.EntityProcessor;
import com.fincity.saas.entity.processor.jooq.Indexes;
import com.fincity.saas.entity.processor.jooq.Keys;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorNotes.EntityProcessorNotesPath;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorTasks.EntityProcessorTasksPath;
import com.fincity.saas.entity.processor.jooq.tables.EntityProcessorTickets.EntityProcessorTicketsPath;
import com.fincity.saas.entity.processor.jooq.tables.records.EntityProcessorActivitiesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EntityProcessorActivities extends TableImpl<EntityProcessorActivitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>entity_processor.entity_processor_activities</code>
     */
    public static final EntityProcessorActivities ENTITY_PROCESSOR_ACTIVITIES = new EntityProcessorActivities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityProcessorActivitiesRecord> getRecordType() {
        return EntityProcessorActivitiesRecord.class;
    }

    /**
     * The column <code>entity_processor.entity_processor_activities.ID</code>.
     * Primary key.
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.APP_CODE</code>. App
     * Code on which this Activity was created.
     */
    public final TableField<EntityProcessorActivitiesRecord, String> APP_CODE = createField(DSL.name("APP_CODE"), SQLDataType.CHAR(64).nullable(false), this, "App Code on which this Activity was created.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.CLIENT_CODE</code>.
     * Client Code who created this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, String> CLIENT_CODE = createField(DSL.name("CLIENT_CODE"), SQLDataType.CHAR(8).nullable(false), this, "Client Code who created this Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.CODE</code>. Unique
     * Code to identify this row.
     */
    public final TableField<EntityProcessorActivitiesRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.CHAR(22).nullable(false), this, "Unique Code to identify this row.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.NAME</code>. Name of
     * the Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(512).nullable(false), this, "Name of the Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.DESCRIPTION</code>.
     * Description for the Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.CLOB, this, "Description for the Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.TICKET_ID</code>.
     * Ticket related to this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> TICKET_ID = createField(DSL.name("TICKET_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Ticket related to this Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.TASK_ID</code>. Task
     * related to this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> TASK_ID = createField(DSL.name("TASK_ID"), SQLDataType.BIGINTUNSIGNED, this, "Task related to this Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.NOTE_ID</code>. Note
     * related to this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> NOTE_ID = createField(DSL.name("NOTE_ID"), SQLDataType.BIGINTUNSIGNED, this, "Note related to this Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.COMMENT</code>.
     * Comment on this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, String> COMMENT = createField(DSL.name("COMMENT"), SQLDataType.CLOB, this, "Comment on this Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.ACTIVITY_DATE</code>.
     * Date of the Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, LocalDateTime> ACTIVITY_DATE = createField(DSL.name("ACTIVITY_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "Date of the Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.ACTIVITY_ACTION</code>.
     * Activity Action categories for this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, ActivityAction> ACTIVITY_ACTION = createField(DSL.name("ACTIVITY_ACTION"), SQLDataType.VARCHAR(19).nullable(false), this, "Activity Action categories for this Activity.", new EnumConverter<String, ActivityAction>(String.class, ActivityAction.class));

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.ACTOR_ID</code>. ID of
     * the user who performed this activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> ACTOR_ID = createField(DSL.name("ACTOR_ID"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who performed this activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.OBJECT_ENTITY_SERIES</code>.
     * Entity Series of the object associated with this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, EntitySeries> OBJECT_ENTITY_SERIES = createField(DSL.name("OBJECT_ENTITY_SERIES"), SQLDataType.VARCHAR(33).nullable(false).defaultValue(DSL.inline("XXX", SQLDataType.VARCHAR)), this, "Entity Series of the object associated with this Activity.", new EnumConverter<String, EntitySeries>(String.class, EntitySeries.class));

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.OBJECT_ID</code>.
     * Object id of OBJECT_ENTITY_SERIES on which Activity is performed
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> OBJECT_ID = createField(DSL.name("OBJECT_ID"), SQLDataType.BIGINTUNSIGNED, this, "Object id of OBJECT_ENTITY_SERIES on which Activity is performed");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.OBJECT_DATA</code>.
     * Object data of OBJECT_ENTITY_SERIES on which Activity is performed
     */
    public final TableField<EntityProcessorActivitiesRecord, Map> OBJECT_DATA = createField(DSL.name("OBJECT_DATA"), SQLDataType.JSON, this, "Object data of OBJECT_ENTITY_SERIES on which Activity is performed", new JSONtoClassConverter<JSON, Map>(JSON.class, Map.class));

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.TEMP_ACTIVE</code>.
     * Temporary active flag for this Activity.
     */
    public final TableField<EntityProcessorActivitiesRecord, Boolean> TEMP_ACTIVE = createField(DSL.name("TEMP_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "Temporary active flag for this Activity.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.IS_ACTIVE</code>. Flag
     * to check if this Activity is active or not.
     */
    public final TableField<EntityProcessorActivitiesRecord, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("1", SQLDataType.BOOLEAN)), this, "Flag to check if this Activity is active or not.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.CREATED_BY</code>. ID
     * of the user who created this row.
     */
    public final TableField<EntityProcessorActivitiesRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row.");

    /**
     * The column
     * <code>entity_processor.entity_processor_activities.CREATED_AT</code>.
     * Time when this row is created.
     */
    public final TableField<EntityProcessorActivitiesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created.");

    private EntityProcessorActivities(Name alias, Table<EntityProcessorActivitiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EntityProcessorActivities(Name alias, Table<EntityProcessorActivitiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>entity_processor.entity_processor_activities</code> table reference
     */
    public EntityProcessorActivities(String alias) {
        this(DSL.name(alias), ENTITY_PROCESSOR_ACTIVITIES);
    }

    /**
     * Create an aliased
     * <code>entity_processor.entity_processor_activities</code> table reference
     */
    public EntityProcessorActivities(Name alias) {
        this(alias, ENTITY_PROCESSOR_ACTIVITIES);
    }

    /**
     * Create a <code>entity_processor.entity_processor_activities</code> table
     * reference
     */
    public EntityProcessorActivities() {
        this(DSL.name("entity_processor_activities"), null);
    }

    public <O extends Record> EntityProcessorActivities(Table<O> path, ForeignKey<O, EntityProcessorActivitiesRecord> childPath, InverseForeignKey<O, EntityProcessorActivitiesRecord> parentPath) {
        super(path, childPath, parentPath, ENTITY_PROCESSOR_ACTIVITIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EntityProcessorActivitiesPath extends EntityProcessorActivities implements Path<EntityProcessorActivitiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EntityProcessorActivitiesPath(Table<O> path, ForeignKey<O, EntityProcessorActivitiesRecord> childPath, InverseForeignKey<O, EntityProcessorActivitiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EntityProcessorActivitiesPath(Name alias, Table<EntityProcessorActivitiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EntityProcessorActivitiesPath as(String alias) {
            return new EntityProcessorActivitiesPath(DSL.name(alias), this);
        }

        @Override
        public EntityProcessorActivitiesPath as(Name alias) {
            return new EntityProcessorActivitiesPath(alias, this);
        }

        @Override
        public EntityProcessorActivitiesPath as(Table<?> alias) {
            return new EntityProcessorActivitiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : EntityProcessor.ENTITY_PROCESSOR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ENTITY_PROCESSOR_ACTIVITIES_IDX0_ACTIVITIES_AC_CC);
    }

    @Override
    public Identity<EntityProcessorActivitiesRecord, ULong> getIdentity() {
        return (Identity<EntityProcessorActivitiesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<EntityProcessorActivitiesRecord> getPrimaryKey() {
        return Keys.KEY_ENTITY_PROCESSOR_ACTIVITIES_PRIMARY;
    }

    @Override
    public List<UniqueKey<EntityProcessorActivitiesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ENTITY_PROCESSOR_ACTIVITIES_UK1_ACTIVITIES_CODE);
    }

    @Override
    public List<ForeignKey<EntityProcessorActivitiesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK1_ACTIVITIES_TICKET_ID, Keys.FK2_ACTIVITIES_TASK_ID, Keys.FK3_ACTIVITIES_NOTE_ID);
    }

    private transient EntityProcessorTicketsPath _entityProcessorTickets;

    /**
     * Get the implicit join path to the
     * <code>entity_processor.entity_processor_tickets</code> table.
     */
    public EntityProcessorTicketsPath entityProcessorTickets() {
        if (_entityProcessorTickets == null)
            _entityProcessorTickets = new EntityProcessorTicketsPath(this, Keys.FK1_ACTIVITIES_TICKET_ID, null);

        return _entityProcessorTickets;
    }

    private transient EntityProcessorTasksPath _entityProcessorTasks;

    /**
     * Get the implicit join path to the
     * <code>entity_processor.entity_processor_tasks</code> table.
     */
    public EntityProcessorTasksPath entityProcessorTasks() {
        if (_entityProcessorTasks == null)
            _entityProcessorTasks = new EntityProcessorTasksPath(this, Keys.FK2_ACTIVITIES_TASK_ID, null);

        return _entityProcessorTasks;
    }

    private transient EntityProcessorNotesPath _entityProcessorNotes;

    /**
     * Get the implicit join path to the
     * <code>entity_processor.entity_processor_notes</code> table.
     */
    public EntityProcessorNotesPath entityProcessorNotes() {
        if (_entityProcessorNotes == null)
            _entityProcessorNotes = new EntityProcessorNotesPath(this, Keys.FK3_ACTIVITIES_NOTE_ID, null);

        return _entityProcessorNotes;
    }

    @Override
    public EntityProcessorActivities as(String alias) {
        return new EntityProcessorActivities(DSL.name(alias), this);
    }

    @Override
    public EntityProcessorActivities as(Name alias) {
        return new EntityProcessorActivities(alias, this);
    }

    @Override
    public EntityProcessorActivities as(Table<?> alias) {
        return new EntityProcessorActivities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorActivities rename(String name) {
        return new EntityProcessorActivities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorActivities rename(Name name) {
        return new EntityProcessorActivities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorActivities rename(Table<?> name) {
        return new EntityProcessorActivities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorActivities where(Condition condition) {
        return new EntityProcessorActivities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorActivities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorActivities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorActivities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorActivities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorActivities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorActivities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorActivities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorActivities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorActivities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
