/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.entity.processor.jooq.tables;


import com.fincity.saas.entity.processor.jooq.EntityProcessor;
import com.fincity.saas.entity.processor.jooq.Keys;
import com.fincity.saas.entity.processor.jooq.enums.EntityProcessorTicketPeDuplicationRulesPhoneNumberAndEmailType;
import com.fincity.saas.entity.processor.jooq.tables.records.EntityProcessorTicketPeDuplicationRulesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EntityProcessorTicketPeDuplicationRules extends TableImpl<EntityProcessorTicketPeDuplicationRulesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules</code>
     */
    public static final EntityProcessorTicketPeDuplicationRules ENTITY_PROCESSOR_TICKET_PE_DUPLICATION_RULES = new EntityProcessorTicketPeDuplicationRules();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityProcessorTicketPeDuplicationRulesRecord> getRecordType() {
        return EntityProcessorTicketPeDuplicationRulesRecord.class;
    }

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.ID</code>.
     * Primary key.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.APP_CODE</code>.
     * App Code on which this Rule was created.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, String> APP_CODE = createField(DSL.name("APP_CODE"), SQLDataType.CHAR(64).nullable(false), this, "App Code on which this Rule was created.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.CLIENT_CODE</code>.
     * Client Code who created this Rule.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, String> CLIENT_CODE = createField(DSL.name("CLIENT_CODE"), SQLDataType.CHAR(8).nullable(false), this, "Client Code who created this Rule.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.CODE</code>.
     * Unique Code to identify this row.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.CHAR(22).nullable(false), this, "Unique Code to identify this row.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.NAME</code>.
     * Name of the Rule.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(64).nullable(false), this, "Name of the Rule.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.DESCRIPTION</code>.
     * Description for the Rule.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.CLOB, this, "Description for the Rule.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.PHONE_NUMBER_AND_EMAIL_TYPE</code>.
     * Phone Number and email type for this client.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, EntityProcessorTicketPeDuplicationRulesPhoneNumberAndEmailType> PHONE_NUMBER_AND_EMAIL_TYPE = createField(DSL.name("PHONE_NUMBER_AND_EMAIL_TYPE"), SQLDataType.VARCHAR(22).nullable(false).defaultValue(DSL.inline("PHONE_NUMBER_OR_EMAIL", SQLDataType.VARCHAR)).asEnumDataType(EntityProcessorTicketPeDuplicationRulesPhoneNumberAndEmailType.class), this, "Phone Number and email type for this client.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.TEMP_ACTIVE</code>.
     * Temporary active flag for this Rule.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, Boolean> TEMP_ACTIVE = createField(DSL.name("TEMP_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "Temporary active flag for this Rule.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.IS_ACTIVE</code>.
     * Flag to check if this Rule is active or not.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("1", SQLDataType.BOOLEAN)), this, "Flag to check if this Rule is active or not.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.CREATED_BY</code>.
     * ID of the user who created this row.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.CREATED_AT</code>.
     * Time when this row is created.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.UPDATED_BY</code>.
     * ID of the user who updated this row.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row.");

    /**
     * The column
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules.UPDATED_AT</code>.
     * Time when this row is updated.
     */
    public final TableField<EntityProcessorTicketPeDuplicationRulesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated.");

    private EntityProcessorTicketPeDuplicationRules(Name alias, Table<EntityProcessorTicketPeDuplicationRulesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EntityProcessorTicketPeDuplicationRules(Name alias, Table<EntityProcessorTicketPeDuplicationRulesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules</code>
     * table reference
     */
    public EntityProcessorTicketPeDuplicationRules(String alias) {
        this(DSL.name(alias), ENTITY_PROCESSOR_TICKET_PE_DUPLICATION_RULES);
    }

    /**
     * Create an aliased
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules</code>
     * table reference
     */
    public EntityProcessorTicketPeDuplicationRules(Name alias) {
        this(alias, ENTITY_PROCESSOR_TICKET_PE_DUPLICATION_RULES);
    }

    /**
     * Create a
     * <code>entity_processor.entity_processor_ticket_pe_duplication_rules</code>
     * table reference
     */
    public EntityProcessorTicketPeDuplicationRules() {
        this(DSL.name("entity_processor_ticket_pe_duplication_rules"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : EntityProcessor.ENTITY_PROCESSOR;
    }

    @Override
    public Identity<EntityProcessorTicketPeDuplicationRulesRecord, ULong> getIdentity() {
        return (Identity<EntityProcessorTicketPeDuplicationRulesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<EntityProcessorTicketPeDuplicationRulesRecord> getPrimaryKey() {
        return Keys.KEY_ENTITY_PROCESSOR_TICKET_PE_DUPLICATION_RULES_PRIMARY;
    }

    @Override
    public List<UniqueKey<EntityProcessorTicketPeDuplicationRulesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ENTITY_PROCESSOR_TICKET_PE_DUPLICATION_RULES_UK1_PTCR_CODE, Keys.KEY_ENTITY_PROCESSOR_TICKET_PE_DUPLICATION_RULES_UK2_AC_CC_PNET);
    }

    @Override
    public EntityProcessorTicketPeDuplicationRules as(String alias) {
        return new EntityProcessorTicketPeDuplicationRules(DSL.name(alias), this);
    }

    @Override
    public EntityProcessorTicketPeDuplicationRules as(Name alias) {
        return new EntityProcessorTicketPeDuplicationRules(alias, this);
    }

    @Override
    public EntityProcessorTicketPeDuplicationRules as(Table<?> alias) {
        return new EntityProcessorTicketPeDuplicationRules(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules rename(String name) {
        return new EntityProcessorTicketPeDuplicationRules(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules rename(Name name) {
        return new EntityProcessorTicketPeDuplicationRules(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules rename(Table<?> name) {
        return new EntityProcessorTicketPeDuplicationRules(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules where(Condition condition) {
        return new EntityProcessorTicketPeDuplicationRules(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorTicketPeDuplicationRules where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorTicketPeDuplicationRules where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorTicketPeDuplicationRules where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityProcessorTicketPeDuplicationRules where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityProcessorTicketPeDuplicationRules whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
