spring:
  application:
    name: entity-processor
  freemarker:
    check-template-location: false
  r2dbc:
    url: ${entity-processor.db.url}
    username: ${entity-processor.db.username}
    password: ${entity-processor.db.password}
    pool:
      initial-size: 2
      max-size: 4
      max-idle-time: 30m
      validation-query: SELECT 1
    flyway:
      enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${entity-processor.db.flyway.url}
      user: ${entity-processor.db.username}
      password: ${entity-processor.db.password}
    data:
      mongodb:
        uri: ${core.mongo.uri}
    boot:
      admin:
        client:
          instance:
            name: entity-processor
    servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1
    cloud:
      gateway:
        routes:
          - id: entity-processor
            uri: lb://entity/processor
            predicates:
              - Path=/api/entity/processor/**, /*/api/entity/processor/**, /*/*/api/entity/processor/**, /*/*/*/api/entity/processor/**, /*/*/*/*/api/entity/processor/**, /*/*/*/*/*/api/entity/processor/**, /*/*/*/*/*/*/api/entity/processor/**, /*/*/*/*/*/*/api/entity/processor/**, /*/*/*/*/*/*/*/api/entity/processor/**, /*/*/*/*/*/*/*/*/api/entity/processor/**, /*/*/*/*/*/*/*/*/*/api/entity/processor/**,
    rabbitmq:
      host: ${mq.host}
      port: ${mq.port}
      username: ${mq.username}
      password: ${mq.password}

management:
  endpoint:
    flyway:
      enabled: true

redis:
  cache:
    prefix: epro
