spring:
  application:
    name: files
  datasource:
    url: ${files.db.url}
    username: ${files.db.username}
    password: ${files.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    minimum-idle: 2
    maximum-pool-size: 4
    idle-timeout: 1800000 # 30 minutes in ms
    connection-test-query: SELECT 1
  flyway:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${files.db.flyway.url}
    user: ${files.db.username}
    password: ${files.db.password}
  boot:
    admin:
      client:
        instance:
          name: Files
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    gateway:
      routes:
        - id: files
          uri: lb://files
          predicates:
            - Path=/api/files/**, /*/api/files/**, /*/*/api/files/**, /*/*/*/api/files/**, /*/*/*/*/api/files/**, /*/*/*/*/*/api/files/**, /*/*/*/*/*/*/api/files/**, /*/*/*/*/*/*/*/api/files/**, /*/*/*/*/*/*/*/*/api/files/**, /*/*/*/*/*/*/*/*/*/api/files/**,

management:
  endpoint:
    flyway:
      enabled: true

redis:
  cache:
    prefix: fil
