spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security
          uri: lb://security
          predicates:
            - Path=/api/security/**, /*/api/security/**, /*/*/api/security/**, /*/*/*/api/security/**, /*/*/*/*/api/security/**, /*/*/*/*/*/api/security/**, /*/*/*/*/*/*/api/security/**, /*/*/*/*/*/*/*/api/security/**, /*/*/*/*/*/*/*/*/api/security/**, /*/*/*/*/*/*/*/*/api/security/**,
        - id: files
          uri: lb://files
          predicates:
            - Path=/api/files/**, /*/api/files/**, /*/*/api/files/**, /*/*/*/api/files/**, /*/*/*/*/api/files/**, /*/*/*/*/*/api/files/**, /*/*/*/*/*/*/api/files/**, /*/*/*/*/*/*/*/api/files/**,, /*/*/*/*/*/*/*/*/api/files/**, /*/*/*/*/*/*/*/*/api/files/**,
        - id: data
          uri: lb://data
          predicates:
            - Path=/api/data/**, /*/api/data/**, /*/*/api/data/**, /*/*/*/api/data/**, /*/*/*/*/api/data/**, /*/*/*/*/*/api/data/**, /*/*/*/*/*/*/api/data/**, /*/*/*/*/*/*/*/api/data/**, /*/*/*/*/*/*/*/*/api/data/**, /*/*/*/*/*/*/*/*/api/data/**,
        - id: core
          uri: lb://core
          predicates:
            - Path=/api/core/**, /*/api/core/**, /*/*/api/core/**, /*/*/*/api/core/**, /*/*/*/*/api/core/**, /*/*/*/*/*/api/core/**, /*/*/*/*/*/*/api/core/**, /*/*/*/*/*/*/*/api/core/**, /*/*/*/*/*/*/*/*/api/core/**, /*/*/*/*/*/*/*/*/api/core/**,
        - id: schedular
          uri: lb://schedular
          predicates:
            - Path=/api/schedular/**, /*/api/schedular/**, /*/*/api/schedular/**, /*/*/*/api/schedular/**, /*/*/*/*/api/schedular/**, /*/*/*/*/*/api/schedular/**, /*/*/*/*/*/*/api/schedular/**, /*/*/*/*/*/*/*/api/schedular/**, /*/*/*/*/*/*/*/*/api/schedular/**, /*/*/*/*/*/*/*/*/api/schedular/**,
        - id: multi
          uri: lb://multi
          predicates:
            - Path=/api/multi/**, /*/api/multi/**, /*/*/api/multi/**, /*/*/*/api/multi/**, /*/*/*/*/api/multi/**, /*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/*/*/api/multi/**,
        - id: entity-collector
          uri: lb://entity-collector
          predicates:
            - Path=/api/entity/collector/**, /*/api/entity/collector/**, /*/*/api/entity/collector/**, /*/*/*/api/entity/collector/**, /*/*/*/*/api/entity/collector/**, /*/*/*/*/*/api/entity/collector/**, /*/*/*/*/*/*/api/entity/collector/**, /*/*/*/*/*/*/*/api/entity/collector/**, /*/*/*/*/*/*/*/*/api/entity/collector/**, /*/*/*/*/*/*/*/*/api/entity/collector/**,
        - id: ui
          uri: lb://ui
          predicates:
            - Path=/**
  boot:
    admin:
      client:
        instance:
          name: Gateway

redis:
  cache:
    prefix: gtw
