spring:
  application:
    name: worker
  
  r2dbc:
    url: ${worker.db.url}
    username: ${worker.db.username}
    password: ${worker.db.password}
    pool:
      initial-size: 2
      max-size: 4
      max-idle-time: 30m
      validation-query: SELECT 1
    flyway:
      enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${worker.db.flyway.url}
      user: ${worker.db.username}
      password: ${worker.db.password}
    boot:
      admin:
        client:
          instance:
            name: worker
    servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1
    cloud:
      gateway:
        routes:
          - id: worker
            uri: lb://worker
            predicates:
              - Path=/api/worker/**, /*/api/worker/**, /*/*/api/worker/**, /*/*/*/api/worker/**, /*/*/*/*/api/worker/**, /*/*/*/*/*/api/worker/**, /*/*/*/*/*/*/api/worker/**, /*/*/*/*/*/*/api/worker/**, /*/*/*/*/*/*/*/api/worker/**, /*/*/*/*/*/*/*/*/api/worker/**, /*/*/*/*/*/*/*/*/*/api/worker/**,

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    scheduler-name: WorkerScheduler
    auto-startup: true
    startup-delay: 0s
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    datasource:
      name: quartzDS
      driver: com.mysql.cj.jdbc.Driver
      url: ${worker.qdb.url}
      username: ${worker.qdb.username}
      password: ${worker.qdb.password}
    properties:
      scheduler:
        instanceName: WorkerScheduler
        instanceId: AUTO
        skipUpdateCheck: true
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        dataSource: quartzDS
        tablePrefix: QRTZ_
        isClustered: true
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 5

management:
  endpoint:
    flyway:
      enabled: true

redis:
  cache:
    prefix: wor