/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.entity.processor.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * User distribution strategy for this rule.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum EntityProcessorProductTemplateRulesUserDistributionType implements EnumType {

    ROUND_ROBIN("ROUND_ROBIN"),

    PERCENTAGE("PERCENTAGE"),

    WEIGHTED("WEIGHTED"),

    LOAD_BALANCED("LOAD_BALANCED"),

    PRIORITY_QUEUE("PRIORITY_QUEUE"),

    RANDOM("RANDOM"),

    HYBRID("HYBRID");

    private final String literal;

    private EntityProcessorProductTemplateRulesUserDistributionType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static EntityProcessorProductTemplateRulesUserDistributionType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(EntityProcessorProductTemplateRulesUserDistributionType.class, literal);
    }
}
