/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.entity.processor.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * Type of Value Template.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum EntityProcessorProductTemplatesProductTemplateType implements EnumType {

    ENTITY("ENTITY"),

    PRODUCT("PRODUCT");

    private final String literal;

    private EntityProcessorProductTemplatesProductTemplateType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static EntityProcessorProductTemplatesProductTemplateType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(EntityProcessorProductTemplatesProductTemplateType.class, literal);
    }
}
