/*
 * This file is generated by jOOQ.
 */
package com.modlix.saas.adzump.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * Type of the action taken
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum AdzumpActionAuditActionType implements EnumType {

    SHIFT_BUDGET("SHIFT_BUDGET"),

    ADJUST_BID("ADJUST_BID"),

    REFINE_AUDIENCE("REFINE_AUDIENCE"),

    ADD_NEGATIVE_KEYWORD("ADD_NEGATIVE_KEYWORD"),

    PAUSE_ENTITY("PAUSE_ENTITY"),

    ROTATE_CREATIVE("ROTATE_CREATIVE"),

    REQUEST_VARIANT("REQUEST_VARIANT");

    private final String literal;

    private AdzumpActionAuditActionType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static AdzumpActionAuditActionType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AdzumpActionAuditActionType.class, literal);
    }
}
