/*
 * This file is generated by jOOQ.
 */
package com.fincity.security.jooq.tables;


import com.fincity.security.jooq.Indexes;
import com.fincity.security.jooq.Keys;
import com.fincity.security.jooq.Security;
import com.fincity.security.jooq.tables.SecurityApp.SecurityAppPath;
import com.fincity.security.jooq.tables.SecurityClient.SecurityClientPath;
import com.fincity.security.jooq.tables.records.SecurityAppSsoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAppSso extends TableImpl<SecurityAppSsoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_app_sso</code>
     */
    public static final SecurityAppSso SECURITY_APP_SSO = new SecurityAppSso();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityAppSsoRecord> getRecordType() {
        return SecurityAppSsoRecord.class;
    }

    /**
     * The column <code>security.security_app_sso.ID</code>. Primary key
     */
    public final TableField<SecurityAppSsoRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_app_sso.CLIENT_ID</code>. Client ID
     */
    public final TableField<SecurityAppSsoRecord, ULong> CLIENT_ID = createField(DSL.name("CLIENT_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Client ID");

    /**
     * The column <code>security.security_app_sso.APP_ID</code>. Application ID
     */
    public final TableField<SecurityAppSsoRecord, ULong> APP_ID = createField(DSL.name("APP_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Application ID");

    /**
     * The column <code>security.security_app_sso.TO_APP_ID</code>. TO
     * Application ID
     */
    public final TableField<SecurityAppSsoRecord, ULong> TO_APP_ID = createField(DSL.name("TO_APP_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "TO Application ID");

    /**
     * The column <code>security.security_app_sso.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public final TableField<SecurityAppSsoRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_app_sso.CREATED_AT</code>. Time when
     * this row is created
     */
    public final TableField<SecurityAppSsoRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_app_sso.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public final TableField<SecurityAppSsoRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_app_sso.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public final TableField<SecurityAppSsoRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityAppSso(Name alias, Table<SecurityAppSsoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityAppSso(Name alias, Table<SecurityAppSsoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_app_sso</code> table reference
     */
    public SecurityAppSso(String alias) {
        this(DSL.name(alias), SECURITY_APP_SSO);
    }

    /**
     * Create an aliased <code>security.security_app_sso</code> table reference
     */
    public SecurityAppSso(Name alias) {
        this(alias, SECURITY_APP_SSO);
    }

    /**
     * Create a <code>security.security_app_sso</code> table reference
     */
    public SecurityAppSso() {
        this(DSL.name("security_app_sso"), null);
    }

    public <O extends Record> SecurityAppSso(Table<O> path, ForeignKey<O, SecurityAppSsoRecord> childPath, InverseForeignKey<O, SecurityAppSsoRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_APP_SSO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityAppSsoPath extends SecurityAppSso implements Path<SecurityAppSsoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityAppSsoPath(Table<O> path, ForeignKey<O, SecurityAppSsoRecord> childPath, InverseForeignKey<O, SecurityAppSsoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityAppSsoPath(Name alias, Table<SecurityAppSsoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityAppSsoPath as(String alias) {
            return new SecurityAppSsoPath(DSL.name(alias), this);
        }

        @Override
        public SecurityAppSsoPath as(Name alias) {
            return new SecurityAppSsoPath(alias, this);
        }

        @Override
        public SecurityAppSsoPath as(Table<?> alias) {
            return new SecurityAppSsoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SECURITY_APP_SSO_FK1_APP_SSO_ACCESS_APP_ID);
    }

    @Override
    public Identity<SecurityAppSsoRecord, ULong> getIdentity() {
        return (Identity<SecurityAppSsoRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityAppSsoRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_APP_SSO_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityAppSsoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_APP_SSO_UK1_APP_SSO_CLIENT);
    }

    @Override
    public List<ForeignKey<SecurityAppSsoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK1_APP_SSO_APP_ID, Keys.FK1_APP_SSO_CLIENT_ID, Keys.FK1_APP_SSO_TO_APP_ID);
    }

    private transient SecurityAppPath _fk1AppSsoAppId;

    /**
     * Get the implicit join path to the <code>security.security_app</code>
     * table, via the <code>FK1_APP_SSO_APP_ID</code> key.
     */
    public SecurityAppPath fk1AppSsoAppId() {
        if (_fk1AppSsoAppId == null)
            _fk1AppSsoAppId = new SecurityAppPath(this, Keys.FK1_APP_SSO_APP_ID, null);

        return _fk1AppSsoAppId;
    }

    private transient SecurityClientPath _securityClient;

    /**
     * Get the implicit join path to the <code>security.security_client</code>
     * table.
     */
    public SecurityClientPath securityClient() {
        if (_securityClient == null)
            _securityClient = new SecurityClientPath(this, Keys.FK1_APP_SSO_CLIENT_ID, null);

        return _securityClient;
    }

    private transient SecurityAppPath _fk1AppSsoToAppId;

    /**
     * Get the implicit join path to the <code>security.security_app</code>
     * table, via the <code>FK1_APP_SSO_TO_APP_ID</code> key.
     */
    public SecurityAppPath fk1AppSsoToAppId() {
        if (_fk1AppSsoToAppId == null)
            _fk1AppSsoToAppId = new SecurityAppPath(this, Keys.FK1_APP_SSO_TO_APP_ID, null);

        return _fk1AppSsoToAppId;
    }

    @Override
    public SecurityAppSso as(String alias) {
        return new SecurityAppSso(DSL.name(alias), this);
    }

    @Override
    public SecurityAppSso as(Name alias) {
        return new SecurityAppSso(alias, this);
    }

    @Override
    public SecurityAppSso as(Table<?> alias) {
        return new SecurityAppSso(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityAppSso rename(String name) {
        return new SecurityAppSso(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityAppSso rename(Name name) {
        return new SecurityAppSso(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityAppSso rename(Table<?> name) {
        return new SecurityAppSso(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityAppSso where(Condition condition) {
        return new SecurityAppSso(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityAppSso where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityAppSso where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityAppSso where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityAppSso where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityAppSso where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityAppSso where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityAppSso where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityAppSso whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityAppSso whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
