ALTER TABLE `entity_processor`.`entity_processor_activities`
    CHANGE COLUMN `Activity_DATE` `ACTIVITY_DATE` TIMESTAMP NOT NULL COMMENT 'Date of the Activity.',
    CHANGE COLUMN `Activity_ACTION` `ACTIVITY_ACTION` ENUM (
        'CREATE',
        'RE_INQUIRY',
        'QUALIFY',
        'DISQUALIFY',
        'DISCARD',
        'IMPORT',
        'STATUS_CREATE',
        'STAGE_UPDATE',
        'TASK_CREATE',
        'TASK_COMPLETE',
        'TASK_CANCELLED',
        'TASK_DELETE',
        'REMINDER_SET',
        'DOCUMENT_UPLOAD',
        'DOCUMENT_DOWNLOAD',
        'DOCUMENT_DELETE',
        'NOTE_ADD',
        'NOTE_DELETE',
        'ASSIGN',
        'REASSIGN',
        'REASSIGN_SYSTEM',
        'OWNERSHIP_TRANSFER',
        'CALL_LOG',
        'WHATSAPP',
        'EMAIL_SENT',
        'SMS_SENT',
        'FIELD_UPDATE',
        'CUSTOM_FIELD_UPDATE',
        'LOCATION_UPDATE',
        'OTHER'
        )
        NOT NULL COMMENT 'Activity Action categories for this Activity.';
