ALTER TABLE `entity_processor`.`entity_processor_tickets`
    ADD INDEX `IDX1_TICKETS_AC_CC_ASSIGNED_USER` (`APP_CODE`, `CLIENT_CODE`, `ASSIGNED_USER_ID`),
    ADD INDEX `IDX2_TICKETS_AC_CC_CLIENT_ID` (`APP_CODE`, `CLIENT_CODE`, `CLIENT_ID`),
    ADD INDEX `IDX3_TICKETS_AC_CC_CREATED_BY` (`APP_CODE`, `CLIENT_CODE`, `CREATED_BY`),
    ADD INDEX `IDX4_TICKETS_AC_CC_PRODUCT_ACTIVE` (`APP_CODE`, `CLIENT_CODE`, `PRODUCT_ID`, `IS_ACTIVE`);
