ALTER TABLE `entity_processor`.`entity_processor_tasks`
    ADD INDEX `IDX1_TASKS_AC_CC_CES_CREATED_BY` (`APP_CODE`, `CLIENT_CODE`, `CONTENT_ENTITY_SERIES`, `CREATED_BY`),
    ADD INDEX `IDX2_TASKS_AC_CC_CES_TICKET_ID` (`APP_CODE`, `CLIENT_CODE`, `CONTENT_ENTITY_SERIES`, `TICKET_ID`);
