ALTER TABLE `entity_processor`.`entity_processor_partners`
    ADD COLUMN `CLIENT_NAME` VARCHAR(512) NULL AFTER `CLIENT_ID`,
    ADD COLUMN `ACTIVE_USERS` INT UNSIGNED NOT NULL DEFAULT 0 AFTER `CLIENT_NAME`,
    ADD COLUMN `TOTAL_TICKETS` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ACTIVE_USERS`,
    ADD COLUMN `USER_NAMES` TEXT NULL AFTER `TOTAL_TICKETS`,
    ADD COLUMN `USER_PHONES` TEXT NULL AFTER `USER_NAMES`,
    ADD COLUMN `CLIENT_MANAGER_IDS` TEXT NULL AFTER `USER_PHONES`,
    ADD COLUMN `DENORM_UPDATED_AT` TIMESTAMP NULL AFTER `CLIENT_MANAGER_IDS`;

ALTER TABLE `entity_processor`.`entity_processor_partners`
    ADD INDEX `IDX1_PARTNERS_TOTAL_TICKETS` (`APP_CODE`, `CLIENT_CODE`, `TOTAL_TICKETS`),
    ADD INDEX `IDX2_PARTNERS_ACTIVE_USERS` (`APP_CODE`, `CLIENT_CODE`, `ACTIVE_USERS`),
    ADD INDEX `IDX3_PARTNERS_CLIENT_NAME` (`APP_CODE`, `CLIENT_CODE`, `CLIENT_NAME`(191)),
    ADD FULLTEXT INDEX `FT1_PARTNERS_USER_NAMES` (`USER_NAMES`);
