ALTER TABLE `entity_processor`.`entity_processor_tasks`
    ADD COLUMN `IS_COMPLETED` TINYINT DEFAULT 0 NOT NULL COMMENT 'Flag to tell, is the task Completed' AFTER `TASK_PRIORITY`,
    ADD COLUMN `COMPLETED_DATE` TIMESTAMP NULL COMMENT 'Timestamp when this task was Completed' AFTER `IS_COMPLETED`,
    ADD COLUMN `IS_CANCELLED` TINYINT DEFAULT 0 NOT NULL COMMENT 'Flag to tell, is the task Cancelled' AFTER `COMPLETED_DATE`,
    ADD COLUMN `CANCELLED_DATE` TIMESTAMP NULL COMMENT 'Timestamp when this task was Cancelled' AFTER `IS_CANCELLED`,
    ADD COLUMN `IS_DELAYED` TINYINT DEFAULT 0 NOT NULL COMMENT 'Error Message' AFTER `CANCELLED_DATE`;
