/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.message.jooq.tables.records;


import com.fincity.saas.message.enums.dispatch.DispatchChannel;
import com.fincity.saas.message.enums.dispatch.DispatchEventType;
import com.fincity.saas.message.jooq.tables.MessageDispatchOutbox;

import java.time.LocalDateTime;
import java.util.Map;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageDispatchOutboxRecord extends UpdatableRecordImpl<MessageDispatchOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>message.message_dispatch_outbox.ID</code>. Primary key.
     */
    public MessageDispatchOutboxRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.ID</code>. Primary key.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.APP_CODE</code>. App
     * Code this handoff belongs to.
     */
    public MessageDispatchOutboxRecord setAppCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.APP_CODE</code>. App
     * Code this handoff belongs to.
     */
    public String getAppCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.CLIENT_CODE</code>.
     * Client Code this handoff belongs to.
     */
    public MessageDispatchOutboxRecord setClientCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.CLIENT_CODE</code>.
     * Client Code this handoff belongs to.
     */
    public String getClientCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.CODE</code>. Unique Code
     * to identify this row.
     */
    public MessageDispatchOutboxRecord setCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.CODE</code>. Unique Code
     * to identify this row.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.OWNER_SERVICE</code>.
     * Dispatch target, taken from the number the event arrived on.
     */
    public MessageDispatchOutboxRecord setOwnerService(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.OWNER_SERVICE</code>.
     * Dispatch target, taken from the number the event arrived on.
     */
    public String getOwnerService() {
        return (String) get(4);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.CHANNEL</code>. Which
     * handler family this routes to.
     */
    public MessageDispatchOutboxRecord setChannel(DispatchChannel value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.CHANNEL</code>. Which
     * handler family this routes to.
     */
    public DispatchChannel getChannel() {
        return (DispatchChannel) get(5);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.EVENT_KEY</code>. The
     * provider's own id for the thing: Meta message id, or Exotel call Sid. The
     * idempotency key, which the consumer upserts on, so replay and
     * out-of-order delivery are both safe.
     */
    public MessageDispatchOutboxRecord setEventKey(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.EVENT_KEY</code>. The
     * provider's own id for the thing: Meta message id, or Exotel call Sid. The
     * idempotency key, which the consumer upserts on, so replay and
     * out-of-order delivery are both safe.
     */
    public String getEventKey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.EVENT_TYPE</code>. What
     * happened. Every kind rides the same outbox on the same key.
     */
    public MessageDispatchOutboxRecord setEventType(DispatchEventType value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.EVENT_TYPE</code>. What
     * happened. Every kind rides the same outbox on the same key.
     */
    public DispatchEventType getEventType() {
        return (DispatchEventType) get(7);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.PAYLOAD</code>. Full
     * dispatch body, so a replay needs no re-parse of the original webhook.
     */
    public MessageDispatchOutboxRecord setPayload(Map value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.PAYLOAD</code>. Full
     * dispatch body, so a replay needs no re-parse of the original webhook.
     */
    public Map getPayload() {
        return (Map) get(8);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.ATTEMPTS</code>.
     * Dispatch attempts so far. Drives the sweeper backoff.
     */
    public MessageDispatchOutboxRecord setAttempts(UInteger value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.ATTEMPTS</code>.
     * Dispatch attempts so far. Drives the sweeper backoff.
     */
    public UInteger getAttempts() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.LAST_ERROR</code>. Last
     * dispatch failure, for diagnosis without log archaeology.
     */
    public MessageDispatchOutboxRecord setLastError(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.LAST_ERROR</code>. Last
     * dispatch failure, for diagnosis without log archaeology.
     */
    public String getLastError() {
        return (String) get(10);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.NEXT_ATTEMPT_AT</code>.
     * Earliest next retry. Null means ready now.
     */
    public MessageDispatchOutboxRecord setNextAttemptAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.NEXT_ATTEMPT_AT</code>.
     * Earliest next retry. Null means ready now.
     */
    public LocalDateTime getNextAttemptAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.CREATED_BY</code>. ID of
     * the user who created this row.
     */
    public MessageDispatchOutboxRecord setCreatedBy(ULong value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.CREATED_BY</code>. ID of
     * the user who created this row.
     */
    public ULong getCreatedBy() {
        return (ULong) get(12);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.CREATED_AT</code>. Time
     * when this row is created.
     */
    public MessageDispatchOutboxRecord setCreatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.CREATED_AT</code>. Time
     * when this row is created.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.UPDATED_BY</code>. ID of
     * the user who updated this row.
     */
    public MessageDispatchOutboxRecord setUpdatedBy(ULong value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.UPDATED_BY</code>. ID of
     * the user who updated this row.
     */
    public ULong getUpdatedBy() {
        return (ULong) get(14);
    }

    /**
     * Setter for <code>message.message_dispatch_outbox.UPDATED_AT</code>. Time
     * when this row is updated.
     */
    public MessageDispatchOutboxRecord setUpdatedAt(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>message.message_dispatch_outbox.UPDATED_AT</code>. Time
     * when this row is updated.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageDispatchOutboxRecord
     */
    public MessageDispatchOutboxRecord() {
        super(MessageDispatchOutbox.MESSAGE_DISPATCH_OUTBOX);
    }

    /**
     * Create a detached, initialised MessageDispatchOutboxRecord
     */
    public MessageDispatchOutboxRecord(ULong id, String appCode, String clientCode, String code, String ownerService, DispatchChannel channel, String eventKey, DispatchEventType eventType, Map payload, UInteger attempts, String lastError, LocalDateTime nextAttemptAt, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(MessageDispatchOutbox.MESSAGE_DISPATCH_OUTBOX);

        setId(id);
        setAppCode(appCode);
        setClientCode(clientCode);
        setCode(code);
        setOwnerService(ownerService);
        setChannel(channel);
        setEventKey(eventKey);
        setEventType(eventType);
        setPayload(payload);
        setAttempts(attempts);
        setLastError(lastError);
        setNextAttemptAt(nextAttemptAt);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
