/*
 * This file is generated by jOOQ.
 */
package com.fincity.saas.message.jooq.tables.records;


import com.fincity.saas.message.enums.bridge.WhatsappSessionState;
import com.fincity.saas.message.jooq.tables.MessageWhatsappPhoneNumbers;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * WhatsApp Business phone numbers
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageWhatsappPhoneNumbersRecord extends UpdatableRecordImpl<MessageWhatsappPhoneNumbersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.ID</code>.
     * Primary key.
     */
    public MessageWhatsappPhoneNumbersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.ID</code>.
     * Primary key.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.APP_CODE</code>.
     * App Code related to this WhatsApp phone number.
     */
    public MessageWhatsappPhoneNumbersRecord setAppCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.APP_CODE</code>.
     * App Code related to this WhatsApp phone number.
     */
    public String getAppCode() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.CLIENT_CODE</code>. Client
     * Code related to this WhatsApp phone number.
     */
    public MessageWhatsappPhoneNumbersRecord setClientCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.CLIENT_CODE</code>. Client
     * Code related to this WhatsApp phone number.
     */
    public String getClientCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.USER_ID</code>.
     * ID of the user associated with this WhatsApp phone number.
     */
    public MessageWhatsappPhoneNumbersRecord setUserId(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.USER_ID</code>.
     * ID of the user associated with this WhatsApp phone number.
     */
    public ULong getUserId() {
        return (ULong) get(3);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.PRODUCT_ID</code>. Entity
     * Processor Product Id
     */
    public MessageWhatsappPhoneNumbersRecord setProductId(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.PRODUCT_ID</code>. Entity
     * Processor Product Id
     */
    public ULong getProductId() {
        return (ULong) get(4);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.OWNER_SERVICE</code>. Eureka
     * service id owning conversations on this number, e.g. entity-processor.
     */
    public MessageWhatsappPhoneNumbersRecord setOwnerService(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.OWNER_SERVICE</code>. Eureka
     * service id owning conversations on this number, e.g. entity-processor.
     */
    public String getOwnerService() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.BRIDGE_INSTANCE_ID</code>.
     * Instance holding this session. Authoritative: routing is a table lookup,
     * never a hash and never a balance. Null means unplaced, which for a Cloud
     * API era row is its permanent state.
     */
    public MessageWhatsappPhoneNumbersRecord setBridgeInstanceId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.BRIDGE_INSTANCE_ID</code>.
     * Instance holding this session. Authoritative: routing is a table lookup,
     * never a hash and never a balance. Null means unplaced, which for a Cloud
     * API era row is its permanent state.
     */
    public String getBridgeInstanceId() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.SESSION_STATE</code>.
     * Lifecycle state as the bridge reports it, surfaced verbatim to the UI.
     * COUNTRY_MISMATCH is separate from LOGGED_OUT because it is the only
     * failure here a customer can fix themselves in seconds, and only if told
     * what it is.
     */
    public MessageWhatsappPhoneNumbersRecord setSessionState(WhatsappSessionState value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.SESSION_STATE</code>.
     * Lifecycle state as the bridge reports it, surfaced verbatim to the UI.
     * COUNTRY_MISMATCH is separate from LOGGED_OUT because it is the only
     * failure here a customer can fix themselves in seconds, and only if told
     * what it is.
     */
    public WhatsappSessionState getSessionState() {
        return (WhatsappSessionState) get(7);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.SESSION_REASON</code>. Why
     * the session is in this state. A BANNED row with no reason is
     * unexplainable three months later.
     */
    public MessageWhatsappPhoneNumbersRecord setSessionReason(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.SESSION_REASON</code>. Why
     * the session is in this state. A BANNED row with no reason is
     * unexplainable three months later.
     */
    public String getSessionReason() {
        return (String) get(8);
    }

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.COUNTRY</code>.
     * ISO country of the linked number, established authoritatively at
     * PairSuccess from the linked JID rather than from what the caller
     * declared. Placement and re-verification both read this.
     */
    public MessageWhatsappPhoneNumbersRecord setCountry(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.COUNTRY</code>.
     * ISO country of the linked number, established authoritatively at
     * PairSuccess from the linked JID rather than from what the caller
     * declared. Placement and re-verification both read this.
     */
    public String getCountry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.LINKED_AT</code>.
     * When the number was linked, UTC. Drives the warm-up ramp, which is
     * derived from this and must not be an editable field.
     */
    public MessageWhatsappPhoneNumbersRecord setLinkedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.LINKED_AT</code>.
     * When the number was linked, UTC. Drives the warm-up ramp, which is
     * derived from this and must not be an editable field.
     */
    public LocalDateTime getLinkedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.STATE_SINCE</code>. When
     * SESSION_STATE last changed, UTC. Distinct from UPDATED_AT so a dead
     * session cannot reset its own retirement clock by being touched.
     */
    public MessageWhatsappPhoneNumbersRecord setStateSince(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.STATE_SINCE</code>. When
     * SESSION_STATE last changed, UTC. Distinct from UPDATED_AT so a dead
     * session cannot reset its own retirement clock by being touched.
     */
    public LocalDateTime getStateSince() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.CODE</code>.
     * Unique Code to identify this row.
     */
    public MessageWhatsappPhoneNumbersRecord setCode(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.CODE</code>.
     * Unique Code to identify this row.
     */
    public String getCode() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.WHATSAPP_BUSINESS_ACCOUNT_ID</code>.
     * Meta business account. Null for every bridge session; retained until the
     * Graph API layer is retired.
     */
    public MessageWhatsappPhoneNumbersRecord setWhatsappBusinessAccountId(ULong value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.WHATSAPP_BUSINESS_ACCOUNT_ID</code>.
     * Meta business account. Null for every bridge session; retained until the
     * Graph API layer is retired.
     */
    public ULong getWhatsappBusinessAccountId() {
        return (ULong) get(13);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.DISPLAY_PHONE_NUMBER</code>.
     * Display phone number for WhatsApp Business.
     */
    public MessageWhatsappPhoneNumbersRecord setDisplayPhoneNumber(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.DISPLAY_PHONE_NUMBER</code>.
     * Display phone number for WhatsApp Business.
     */
    public String getDisplayPhoneNumber() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.VERIFIED_NAME</code>.
     * Verified name associated with the phone number.
     */
    public MessageWhatsappPhoneNumbersRecord setVerifiedName(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.VERIFIED_NAME</code>.
     * Verified name associated with the phone number.
     */
    public String getVerifiedName() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.PHONE_NUMBER_ID</code>.
     * WhatsApp phone number ID from Meta.
     */
    public MessageWhatsappPhoneNumbersRecord setPhoneNumberId(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.PHONE_NUMBER_ID</code>.
     * WhatsApp phone number ID from Meta.
     */
    public String getPhoneNumberId() {
        return (String) get(16);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.IS_DEFAULT</code>. Flag to
     * indicate if this is the default phone number.
     */
    public MessageWhatsappPhoneNumbersRecord setIsDefault(Boolean value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.IS_DEFAULT</code>. Flag to
     * indicate if this is the default phone number.
     */
    public Boolean getIsDefault() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>message.message_whatsapp_phone_numbers.IS_ACTIVE</code>.
     * Flag to check if this phone number is active or not.
     */
    public MessageWhatsappPhoneNumbersRecord setIsActive(Boolean value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>message.message_whatsapp_phone_numbers.IS_ACTIVE</code>.
     * Flag to check if this phone number is active or not.
     */
    public Boolean getIsActive() {
        return (Boolean) get(18);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.CREATED_BY</code>. ID of the
     * user who created this row.
     */
    public MessageWhatsappPhoneNumbersRecord setCreatedBy(ULong value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.CREATED_BY</code>. ID of the
     * user who created this row.
     */
    public ULong getCreatedBy() {
        return (ULong) get(19);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.CREATED_AT</code>. Time when
     * this record was created.
     */
    public MessageWhatsappPhoneNumbersRecord setCreatedAt(LocalDateTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.CREATED_AT</code>. Time when
     * this record was created.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.UPDATED_BY</code>. ID of the
     * user who updated this row.
     */
    public MessageWhatsappPhoneNumbersRecord setUpdatedBy(ULong value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.UPDATED_BY</code>. ID of the
     * user who updated this row.
     */
    public ULong getUpdatedBy() {
        return (ULong) get(21);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.UPDATED_AT</code>. Time when
     * this record was last updated.
     */
    public MessageWhatsappPhoneNumbersRecord setUpdatedAt(LocalDateTime value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.UPDATED_AT</code>. Time when
     * this record was last updated.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for
     * <code>message.message_whatsapp_phone_numbers.LINKED_NUMBER_KEY</code>.
     * DISPLAY_PHONE_NUMBER for placed sessions only, NULL otherwise. Exists
     * purely to carry the unique key below.
     */
    public MessageWhatsappPhoneNumbersRecord setLinkedNumberKey(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for
     * <code>message.message_whatsapp_phone_numbers.LINKED_NUMBER_KEY</code>.
     * DISPLAY_PHONE_NUMBER for placed sessions only, NULL otherwise. Exists
     * purely to carry the unique key below.
     */
    public String getLinkedNumberKey() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageWhatsappPhoneNumbersRecord
     */
    public MessageWhatsappPhoneNumbersRecord() {
        super(MessageWhatsappPhoneNumbers.MESSAGE_WHATSAPP_PHONE_NUMBERS);
    }

    /**
     * Create a detached, initialised MessageWhatsappPhoneNumbersRecord
     */
    public MessageWhatsappPhoneNumbersRecord(ULong id, String appCode, String clientCode, ULong userId, ULong productId, String ownerService, String bridgeInstanceId, WhatsappSessionState sessionState, String sessionReason, String country, LocalDateTime linkedAt, LocalDateTime stateSince, String code, ULong whatsappBusinessAccountId, String displayPhoneNumber, String verifiedName, String phoneNumberId, Boolean isDefault, Boolean isActive, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt, String linkedNumberKey) {
        super(MessageWhatsappPhoneNumbers.MESSAGE_WHATSAPP_PHONE_NUMBERS);

        setId(id);
        setAppCode(appCode);
        setClientCode(clientCode);
        setUserId(userId);
        setProductId(productId);
        setOwnerService(ownerService);
        setBridgeInstanceId(bridgeInstanceId);
        setSessionState(sessionState);
        setSessionReason(sessionReason);
        setCountry(country);
        setLinkedAt(linkedAt);
        setStateSince(stateSince);
        setCode(code);
        setWhatsappBusinessAccountId(whatsappBusinessAccountId);
        setDisplayPhoneNumber(displayPhoneNumber);
        setVerifiedName(verifiedName);
        setPhoneNumberId(phoneNumberId);
        setIsDefault(isDefault);
        setIsActive(isActive);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        setLinkedNumberKey(linkedNumberKey);
        resetChangedOnNotNull();
    }
}
