/*
 * This file is generated by jOOQ.
 */
package com.modlix.saas.notification.jooq;


import com.modlix.saas.notification.jooq.tables.NotificationInapp;
import com.modlix.saas.notification.jooq.tables.NotificationPreference;
import com.modlix.saas.notification.jooq.tables.records.NotificationInappRecord;
import com.modlix.saas.notification.jooq.tables.records.NotificationPreferenceRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * notification.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<NotificationInappRecord> KEY_NOTIFICATION_INAPP_PRIMARY = Internal.createUniqueKey(NotificationInapp.NOTIFICATION_INAPP, DSL.name("KEY_notification_inapp_PRIMARY"), new TableField[] { NotificationInapp.NOTIFICATION_INAPP.ID }, true);
    public static final UniqueKey<NotificationPreferenceRecord> KEY_NOTIFICATION_PREFERENCE_PRIMARY = Internal.createUniqueKey(NotificationPreference.NOTIFICATION_PREFERENCE, DSL.name("KEY_notification_preference_PRIMARY"), new TableField[] { NotificationPreference.NOTIFICATION_PREFERENCE.ID }, true);
}
