/*
 * This file is generated by jOOQ.
 */
package com.modlix.saas.notification.jooq;


import com.modlix.saas.notification.jooq.tables.NotificationInapp;
import com.modlix.saas.notification.jooq.tables.NotificationPreference;


/**
 * Convenience access to all tables in notification.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>notification.notification_inapp</code>.
     */
    public static final NotificationInapp NOTIFICATION_INAPP = NotificationInapp.NOTIFICATION_INAPP;

    /**
     * The table <code>notification.notification_preference</code>.
     */
    public static final NotificationPreference NOTIFICATION_PREFERENCE = NotificationPreference.NOTIFICATION_PREFERENCE;
}
