/*
 * This file is generated by jOOQ.
 */
package com.modlix.saas.adzump.jooq.tables.records;


import com.modlix.saas.adzump.jooq.enums.AdzumpExperimentStatus;
import com.modlix.saas.adzump.jooq.tables.AdzumpExperiment;

import java.time.LocalDateTime;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdzumpExperimentRecord extends UpdatableRecordImpl<AdzumpExperimentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>adzump.adzump_experiment.id</code>. Primary key
     */
    public AdzumpExperimentRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.id</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.client_code</code>. Client code
     * (tenant-private)
     */
    public AdzumpExperimentRecord setClientCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.client_code</code>. Client code
     * (tenant-private)
     */
    public String getClientCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.campaign_plan_id</code>.
     * Campaign plan this experiment runs on
     */
    public AdzumpExperimentRecord setCampaignPlanId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.campaign_plan_id</code>.
     * Campaign plan this experiment runs on
     */
    public ULong getCampaignPlanId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.hypothesis</code>. Human
     * hypothesis under test
     */
    public AdzumpExperimentRecord setHypothesis(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.hypothesis</code>. Human
     * hypothesis under test
     */
    public String getHypothesis() {
        return (String) get(3);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.metric</code>. Success metric:
     * blended objective at creative grain (e.g. blendedScore@creative)
     */
    public AdzumpExperimentRecord setMetric(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.metric</code>. Success metric:
     * blended objective at creative grain (e.g. blendedScore@creative)
     */
    public String getMetric() {
        return (String) get(4);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.min_volume_per_variant</code>.
     * Minimum CRM outcome volume per arm before a readout may reach
     * significance
     */
    public AdzumpExperimentRecord setMinVolumePerVariant(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.min_volume_per_variant</code>.
     * Minimum CRM outcome volume per arm before a readout may reach
     * significance
     */
    public Integer getMinVolumePerVariant() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.max_duration_days</code>. Hard
     * duration cap in days; experiment ends INCONCLUSIVE at this cap rather
     * than running unbounded
     */
    public AdzumpExperimentRecord setMaxDurationDays(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.max_duration_days</code>. Hard
     * duration cap in days; experiment ends INCONCLUSIVE at this cap rather
     * than running unbounded
     */
    public Integer getMaxDurationDays() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.status</code>. Experiment
     * lifecycle status
     */
    public AdzumpExperimentRecord setStatus(AdzumpExperimentStatus value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.status</code>. Experiment
     * lifecycle status
     */
    public AdzumpExperimentStatus getStatus() {
        return (AdzumpExperimentStatus) get(7);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.variants</code>. Array of arms
     * {creativeId, attributes, allocation} varying exactly one attribute axis
     */
    public AdzumpExperimentRecord setVariants(JSON value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.variants</code>. Array of arms
     * {creativeId, attributes, allocation} varying exactly one attribute axis
     */
    public JSON getVariants() {
        return (JSON) get(8);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.readout</code>. Computed
     * readout {perVariant array + winner + pValue + significant}; NULL until
     * first measured
     */
    public AdzumpExperimentRecord setReadout(JSON value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.readout</code>. Computed
     * readout {perVariant array + winner + pValue + significant}; NULL until
     * first measured
     */
    public JSON getReadout() {
        return (JSON) get(9);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.started_at</code>. When the
     * experiment started rotating live (RUNNING); NULL while DESIGNED
     */
    public AdzumpExperimentRecord setStartedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.started_at</code>. When the
     * experiment started rotating live (RUNNING); NULL while DESIGNED
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.ended_at</code>. When the
     * experiment reached a terminal readout; NULL while DESIGNED/RUNNING
     */
    public AdzumpExperimentRecord setEndedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.ended_at</code>. When the
     * experiment reached a terminal readout; NULL while DESIGNED/RUNNING
     */
    public LocalDateTime getEndedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.created_by</code>. ID of the
     * user who created this row
     */
    public AdzumpExperimentRecord setCreatedBy(ULong value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.created_by</code>. ID of the
     * user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(12);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.created_at</code>. Time when
     * this row is created
     */
    public AdzumpExperimentRecord setCreatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.created_at</code>. Time when
     * this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.updated_by</code>. ID of the
     * user who updated this row
     */
    public AdzumpExperimentRecord setUpdatedBy(ULong value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.updated_by</code>. ID of the
     * user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(14);
    }

    /**
     * Setter for <code>adzump.adzump_experiment.updated_at</code>. Time when
     * this row is updated
     */
    public AdzumpExperimentRecord setUpdatedAt(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>adzump.adzump_experiment.updated_at</code>. Time when
     * this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdzumpExperimentRecord
     */
    public AdzumpExperimentRecord() {
        super(AdzumpExperiment.ADZUMP_EXPERIMENT);
    }

    /**
     * Create a detached, initialised AdzumpExperimentRecord
     */
    public AdzumpExperimentRecord(ULong id, String clientCode, ULong campaignPlanId, String hypothesis, String metric, Integer minVolumePerVariant, Integer maxDurationDays, AdzumpExperimentStatus status, JSON variants, JSON readout, LocalDateTime startedAt, LocalDateTime endedAt, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(AdzumpExperiment.ADZUMP_EXPERIMENT);

        setId(id);
        setClientCode(clientCode);
        setCampaignPlanId(campaignPlanId);
        setHypothesis(hypothesis);
        setMetric(metric);
        setMinVolumePerVariant(minVolumePerVariant);
        setMaxDurationDays(maxDurationDays);
        setStatus(status);
        setVariants(variants);
        setReadout(readout);
        setStartedAt(startedAt);
        setEndedAt(endedAt);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
